local item = function(char, description, aliases)
  if aliases and aliases ~= "" then
    return { char = char, label = string.format("%s  %s | %s", char, description, aliases) }
  end
  return { char = char, label = string.format("%s  %s", char, description) }
end

local unicode_items = {
  -- arrows
  item("→", "Arrow right", "-> imply map"),
  item("←", "Arrow left", "<-"),
  item("↑", "Arrow up", ""),
  item("↓", "Arrow down", ""),
  item("↔", "Arrow left-right", "<->"),
  item("↕", "Arrow up-down", ""),
  item("↩", "Arrow return left", "back"),
  item("↪", "Arrow return right", "forward"),
  item("↗", "Arrow up-right", ""),
  item("↘", "Arrow down-right", ""),
  item("↙", "Arrow down-left", ""),
  item("↖", "Arrow up-left", ""),
  item("⇒", "Double arrow right", "=>"),
  item("⇐", "Double arrow left", "<="),
  item("⇔", "Double arrow both", "<=>"),
  item("⇑", "Double arrow up", ""),
  item("⇓", "Double arrow down", ""),
  item("⇢", "Arrow right dashed", ""),
  item("⇠", "Arrow left dashed", ""),
  item("↦", "Mapsto right", "|->"),
  item("↤", "Mapsto left", "<-|"),
  item("↝", "Right squiggle arrow", "~>"),
  item("↞", "Two-headed left arrow", "<<-"),
  item("↠", "Two-headed right arrow", "->>"),
  item("↥", "Up harpoon", ""),
  item("↧", "Down harpoon", ""),
  item("↰", "Arrow up-left with hook", ""),
  item("↱", "Arrow up-right with hook", ""),
  item("↲", "Arrow down-left with hook", ""),
  item("↳", "Arrow down-right with hook", ""),
  item("↵", "Down-left arrow", "return"),
  item("⟶", "Long right arrow", "-->"),
  item("⟵", "Long left arrow", "<--"),
  item("⟷", "Long left-right arrow", "<-->"),
  item("⤴", "Arrow right curving up", ""),
  item("⤵", "Arrow right curving down", ""),
  item("➜", "Heavy right arrow", "arrow"),
  item("➤", "Black right arrowhead", "arrow"),

  -- operators and math
  item("≤", "Less than or equal", "<="),
  item("≥", "Greater than or equal", ">="),
  item("≠", "Not equal", "!="),
  item("≈", "Approximately equal", "~="),
  item("≃", "Asymptotically equal to", "simeq"),
  item("≅", "Approximately congruent", "cong"),
  item("≪", "Much less than", "<<"),
  item("≫", "Much greater than", ">>"),
  item("⩽", "Less than or slanted equal", "<="),
  item("⩾", "Greater than or slanted equal", ">="),
  item("≡", "Identical to", "==="),
  item("±", "Plus-minus", "+/-"),
  item("∓", "Minus-plus", "-/+"),
  item("×", "Multiplication", "mul"),
  item("÷", "Division", "div"),
  item("√", "Square root", "sqrt"),
  item("∛", "Cube root", "cuberoot"),
  item("∜", "Fourth root", "fourthroot"),
  item("∑", "Summation", "sum sigma"),
  item("∏", "Product", "prod pi"),
  item("∫", "Integral", "integrate"),
  item("∬", "Double integral", ""),
  item("∮", "Contour integral", ""),
  item("∂", "Partial derivative", "del"),
  item("∇", "Nabla", "gradient del"),
  item("⋅", "Dot operator", "cdot"),
  item("∘", "Ring operator", "compose"),
  item("∗", "Asterisk operator", "ast"),
  item("⊙", "Circled dot operator", "odot"),
  item("⊖", "Circled minus", "ominus"),
  item("∥", "Parallel to", "parallel"),
  item("⊥", "Perpendicular", "perp"),
  item("⊢", "Turnstile", "|-"),
  item("⊣", "Left turnstile", "-|"),
  item("⊨", "Models", "|="),
  item("∞", "Infinity", "infinite"),
  item("∝", "Proportional to", "prop"),
  item("∴", "Therefore", "therefore"),
  item("∵", "Because", "because"),

  -- sets and logic
  item("∈", "Element of", "in set"),
  item("∉", "Not element of", "not in set"),
  item("∋", "Contains as member", "reverse in"),
  item("∅", "Empty set", "null set"),
  item("⊂", "Subset of", "subset"),
  item("⊃", "Superset of", "superset"),
  item("⊆", "Subset or equal", "subseteq"),
  item("⊇", "Superset or equal", "supseteq"),
  item("⊄", "Not a subset of", "nsubset"),
  item("⊅", "Not a superset of", "nsupset"),
  item("∩", "Intersection", "cap"),
  item("∪", "Union", "cup"),
  item("⊎", "Disjoint union", "uplus"),
  item("∖", "Set minus", "setminus"),
  item("∧", "Logical and", "and"),
  item("∨", "Logical or", "or"),
  item("¬", "Logical not", "not"),
  item("⊕", "Exclusive or", "xor"),
  item("⊗", "Tensor / circled times", "otimes"),
  item("∀", "For all", "forall"),
  item("∃", "There exists", "exists"),
  item("∄", "There does not exist", "nexists"),

  -- number sets
  item("ℕ", "Natural numbers", "N"),
  item("ℤ", "Integers", "Z"),
  item("ℚ", "Rational numbers", "Q"),
  item("ℝ", "Real numbers", "R"),
  item("ℂ", "Complex numbers", "C"),

  -- programming and greek
  item("λ", "Lambda", "lambda"),
  item("π", "Pi", "pi"),
  item("Δ", "Delta uppercase", "delta"),
  item("Ω", "Omega uppercase", "omega"),
  item("α", "Alpha", "alpha"),
  item("β", "Beta", "beta"),
  item("γ", "Gamma", "gamma"),
  item("μ", "Mu", "micro"),
  item("σ", "Sigma", "sigma"),
  item("τ", "Tau", "tau"),
  item("φ", "Phi", "phi"),
  item("θ", "Theta", "theta"),
  item("η", "Eta", "eta"),
  item("κ", "Kappa", "kappa"),
  item("ν", "Nu", "nu"),
  item("ξ", "Xi", "xi"),
  item("ρ", "Rho", "rho"),
  item("χ", "Chi", "chi"),
  item("ψ", "Psi", "psi"),

  -- delimiters
  item("⟨", "Angle bracket left", "<"),
  item("⟩", "Angle bracket right", ">"),
  item("⟪", "Double angle bracket left", "<<"),
  item("⟫", "Double angle bracket right", ">>"),
  item("⌈", "Ceiling left", ""),
  item("⌉", "Ceiling right", ""),
  item("⌊", "Floor left", ""),
  item("⌋", "Floor right", ""),
  item("「", "Corner bracket left", ""),
  item("」", "Corner bracket right", ""),
  item("『", "White corner bracket left", ""),
  item("』", "White corner bracket right", ""),
  item("【", "Black lenticular bracket left", ""),
  item("】", "Black lenticular bracket right", ""),
  item("〔", "Tortoise shell bracket left", ""),
  item("〕", "Tortoise shell bracket right", ""),
  item("⌜", "Top left corner", ""),
  item("⌝", "Top right corner", ""),
  item("⌞", "Bottom left corner", ""),
  item("⌟", "Bottom right corner", ""),

  -- box drawing
  item("│", "Box vertical", "pipe"),
  item("─", "Box horizontal", "dash"),
  item("┌", "Box corner top-left", ""),
  item("┐", "Box corner top-right", ""),
  item("└", "Box corner bottom-left", ""),
  item("┘", "Box corner bottom-right", ""),
  item("├", "Box tee left", ""),
  item("┤", "Box tee right", ""),
  item("┬", "Box tee up", ""),
  item("┴", "Box tee down", ""),
  item("┼", "Box cross", ""),
  item("╭", "Rounded corner top-left", ""),
  item("╮", "Rounded corner top-right", ""),
  item("╰", "Rounded corner bottom-left", ""),
  item("╯", "Rounded corner bottom-right", ""),
  item("┏", "Heavy corner top-left", ""),
  item("┓", "Heavy corner top-right", ""),
  item("┗", "Heavy corner bottom-left", ""),
  item("┛", "Heavy corner bottom-right", ""),
  item("╔", "Double corner top-left", ""),
  item("╗", "Double corner top-right", ""),
  item("╚", "Double corner bottom-left", ""),
  item("╝", "Double corner bottom-right", ""),
  item("╠", "Double tee left", ""),
  item("╣", "Double tee right", ""),
  item("╦", "Double tee up", ""),
  item("╩", "Double tee down", ""),
  item("╬", "Double cross", ""),

  -- separators and thematic breaks
  item("―", "Horizontal bar thematic break", "rule"),
  item("⸺", "Two-em dash thematic break", "rule"),
  item("⸻", "Three-em dash thematic break", "rule"),
  item("⎯", "Horizontal scan line", "rule"),
  item("⎺", "Top scan line", "rule"),
  item("﹉", "Dotted overline", "rule"),
  item("﹊", "Wavy overline", "rule"),
  item("﹍", "Dashed overline", "rule"),
  item("━", "Heavy horizontal line", "rule"),
  item("═", "Double horizontal line", "rule"),
  item("╌", "Dashed light horizontal line", "rule"),
  item("╍", "Dashed heavy horizontal line", "rule"),
  item("┄", "Light triple dash horizontal", "rule"),
  item("┅", "Heavy triple dash horizontal", "rule"),
  item("┈", "Light quadruple dash horizontal", "rule"),
  item("┉", "Heavy quadruple dash horizontal", "rule"),
  item("▔", "Upper one eighth block", "rule"),
  item("▀", "Upper half block", "rule"),
  item("▁", "Lower one eighth block", "rule"),
  item("▄", "Lower half block", "rule"),
  item("▅", "Lower five eighths block", "rule"),
  item("▆", "Lower six eighths block", "rule"),
  item("▇", "Lower seven eighths block", "rule"),
  item("█", "Full block", "rule"),
  item("▌", "Left half block", "rule"),
  item("▐", "Right half block", "rule"),
  item("░", "Light shade", "shade"),
  item("▒", "Medium shade", "shade"),
  item("▓", "Dark shade", "shade"),

  -- bullets and markers
  item("•", "Bullet", "bullet"),
  item("◦", "White bullet", "hollow bullet"),
  item("●", "Black circle", "circle"),
  item("○", "White circle", "circle"),
  item("◉", "Fisheye", "circle"),
  item("◌", "Dotted circle", "circle"),
  item("◍", "Circle with vertical fill", "circle"),
  item("▪", "Small black square", "square"),
  item("▫", "Small white square", "square"),
  item("◆", "Black diamond", "diamond"),
  item("◇", "White diamond", "diamond"),
  item("■", "Black square", "square"),
  item("□", "White square", "square"),
  item("▲", "Black triangle up", "triangle"),
  item("△", "White triangle up", "triangle"),
  item("▶", "Black triangle right", "play"),
  item("▷", "White triangle right", "play"),
  item("▼", "Black triangle down", "triangle"),
  item("▽", "White triangle down", "triangle"),
  item("★", "Black star", "star"),
  item("☆", "White star", "star"),
  item("☐", "Ballot box empty", "checkbox unchecked"),
  item("☑", "Ballot box with check", "checkbox checked"),
  item("☒", "Ballot box with X", "checkbox x crossed"),
  item("✓", "Check mark", "check"),
  item("✔", "Heavy check mark", "check"),
  item("✗", "Cross mark", "x"),
  item("✖", "Heavy cross mark", "x"),

  -- punctuation and quotes
  item("…", "Ellipsis", "..."),
  item("—", "Em dash", "emdash"),
  item("–", "En dash", "endash"),
  item("‖", "Double vertical line", "parallel"),
  item("·", "Middle dot", "dot"),
  item("•", "Bullet dot", "dot"),
  item("′", "Prime", "minute"),
  item("″", "Double prime", "second"),
  item("‴", "Triple prime", "third"),
  item("⁗", "Quadruple prime", "fourth"),
  item("‥", "Two dot leader", "leader"),
  item("⋯", "Midline horizontal ellipsis", "ellipsis"),
  item("⋮", "Vertical ellipsis", "ellipsis"),
  item("⋰", "Up right diagonal ellipsis", "ellipsis"),
  item("⋱", "Down right diagonal ellipsis", "ellipsis"),
  item("‽", "Interrobang", "!?"),
  item("¡", "Inverted exclamation", "!"),
  item("¿", "Inverted question", "?"),
  item("‐", "Hyphen", "hyphen"),
  item("‑", "Non-breaking hyphen", "hyphen"),
  item("‒", "Figure dash", "dash"),
  item("※", "Reference mark", "note"),
  item("“", "Left double quote", '"'),
  item("”", "Right double quote", '"'),
  item("‘", "Left single quote", "'"),
  item("’", "Right single quote", "'"),
  item("«", "Left guillemet", "<<"),
  item("»", "Right guillemet", ">>"),
  item("‹", "Single left guillemet", "<"),
  item("›", "Single right guillemet", ">"),
  item("№", "Numero sign", "number"),

  -- misc utility
  item("°", "Degree sign", "degree"),
  item("℃", "Celsius sign", "celsius"),
  item("℉", "Fahrenheit sign", "fahrenheit"),
  item("©", "Copyright", "copyright"),
  item("®", "Registered", "registered"),
  item("™", "Trademark", "tm"),
  item("µ", "Micro sign", "micro"),
  item("§", "Section sign", "section"),
  item("¶", "Pilcrow", "paragraph"),
  item("†", "Dagger", "dagger"),
  item("‡", "Double dagger", "ddagger"),
  item("ℹ", "Information", "info"),
  item("␠", "Symbol for space", "space"),
  item("␣", "Open box for space", "space"),
  item("␉", "Symbol for horizontal tab", "tab"),
  item("⇥", "Rightwards tab", "tab"),
  item("⇤", "Leftwards tab", "tab"),
  item("↹", "Left right tab", "tab"),
  item("␤", "Symbol for line feed", "newline"),
  item("⏎", "Return symbol", "return"),
  item("␛", "Escape symbol", "esc"),
  item("␀", "Null symbol", "nul"),
  item("❖", "Black diamond ornament", "divider"),
  item("✦", "Black four pointed star", "divider"),
  item("✧", "White four pointed star", "divider"),
  item("❉", "Sparkle ornament", "divider"),
  item("❋", "Heavy eight teardrop asterisk", "divider"),
  item("✶", "Six pointed black star", "divider"),
  item("✷", "Eight pointed rectilinear black star", "divider"),
  item("✸", "Heavy eight pointed rectilinear star", "divider"),
  item("✹", "Twelve pointed black star", "divider"),
  item("✺", "Sixteen pointed asterisk", "divider"),
  item("✽", "Heavy teardrop asterisk", "divider"),
  item("❂", "Circled open centre eight pointed star", "divider"),
  item("⟡", "White concave-sided diamond", "divider"),
  item("½", "One half", "1/2"),
  item("¼", "One quarter", "1/4"),
  item("¾", "Three quarters", "3/4"),
  item("⅓", "One third", "1/3"),
  item("⅔", "Two thirds", "2/3"),
  item("⅛", "One eighth", "1/8"),
  item("⅜", "Three eighths", "3/8"),
  item("⅝", "Five eighths", "5/8"),
  item("⅞", "Seven eighths", "7/8"),
  item("⁰", "Superscript zero", "^0"),
  item("¹", "Superscript one", "^1"),
  item("²", "Superscript two", "^2"),
  item("³", "Superscript three", "^3"),
  item("⁴", "Superscript four", "^4"),
  item("⁵", "Superscript five", "^5"),
  item("⁶", "Superscript six", "^6"),
  item("⁷", "Superscript seven", "^7"),
  item("⁸", "Superscript eight", "^8"),
  item("⁹", "Superscript nine", "^9"),
  item("₀", "Subscript zero", "_0"),
  item("₁", "Subscript one", "_1"),
  item("₂", "Subscript two", "_2"),
  item("₃", "Subscript three", "_3"),
  item("₄", "Subscript four", "_4"),
  item("₅", "Subscript five", "_5"),
  item("₆", "Subscript six", "_6"),
  item("₇", "Subscript seven", "_7"),
  item("₈", "Subscript eight", "_8"),
  item("₉", "Subscript nine", "_9"),
  item("€", "Euro", "eur"),
  item("£", "Pound sterling", "gbp"),
  item("¥", "Yen", "jpy"),
  item("₹", "Indian rupee", "inr"),
  item("₩", "South Korean won", "krw"),
  item("₽", "Russian ruble", "rub"),
  item("₪", "Israeli new shekel", "ils"),
  item("₫", "Vietnamese dong", "vnd"),
  item("₦", "Nigerian naira", "ngn"),
  item("₱", "Philippine peso", "php"),
  item("₺", "Turkish lira", "try"),
  item("₴", "Ukrainian hryvnia", "uah"),
  item("₿", "Bitcoin sign", "btc"),
}

local emoji_items = {
  -- top 500 non-flag emojis by global usage from emojitracker.com
  item("❤️", "red heart", "smileys & emotion"),
  item("✅", "check mark button", "symbols"),
  item("✨", "sparkles", "activities"),
  item("😭", "loudly crying face", "smileys & emotion"),
  item("🔥", "fire", "travel & places"),
  item("😂", "face with tears of joy", "smileys & emotion"),
  item("😊", "smiling face with smiling eyes", "smileys & emotion"),
  item("💀", "skull", "smileys & emotion"),
  item("⭐", "star", "travel & places"),
  item("🥹", "face holding back tears", "smileys & emotion"),
  item("🫶", "heart hands", "people & body"),
  item("👀", "eyes", "people & body"),
  item("🎉", "party popper", "activities"),
  item("🙏", "folded hands", "people & body"),
  item("👍", "thumbs up", "people & body"),
  item("✔️", "check mark", "symbols"),
  item("🥰", "smiling face with hearts", "smileys & emotion"),
  item("📍", "round pushpin", "objects"),
  item("😅", "grinning face with sweat", "smileys & emotion"),
  item("👉", "backhand index pointing right", "people & body"),
  item("😍", "smiling face with heart-eyes", "smileys & emotion"),
  item("❌", "cross mark", "symbols"),
  item("🎄", "Christmas tree", "activities"),
  item("🤣", "rolling on the floor laughing", "smileys & emotion"),
  item("🫶🏻", "emoji", "emoji"),
  item("😉", "winking face", "smileys & emotion"),
  item("⚠️", "warning", "symbols"),
  item("➡️", "right arrow", "symbols"),
  item("🤍", "white heart", "smileys & emotion"),
  item("🫡", "saluting face", "smileys & emotion"),
  item("🚀", "rocket", "travel & places"),
  item("🤔", "thinking face", "smileys & emotion"),
  item("👇", "backhand index pointing down", "people & body"),
  item("☀️", "sun", "travel & places"),
  item("❤️‍🩹", "mending heart", "smileys & emotion"),
  item("🎁", "wrapped gift", "activities"),
  item("💙", "blue heart", "smileys & emotion"),
  item("🤩", "star-struck", "smileys & emotion"),
  item("🩷", "pink heart", "smileys & emotion"),
  item("💪", "flexed biceps", "people & body"),
  item("🫦", "biting lip", "people & body"),
  item("☺️", "smiling face", "smileys & emotion"),
  item("🚨", "police car light", "travel & places"),
  item("😎", "smiling face with sunglasses", "smileys & emotion"),
  item("🥺", "pleading face", "smileys & emotion"),
  item("🥳", "partying face", "smileys & emotion"),
  item("😔", "pensive face", "smileys & emotion"),
  item("🔴", "red circle", "symbols"),
  item("🫠", "melting face", "smileys & emotion"),
  item("💡", "light bulb", "objects"),
  item("⬇️", "down arrow", "symbols"),
  item("😁", "beaming face with smiling eyes", "smileys & emotion"),
  item("😘", "face blowing a kiss", "smileys & emotion"),
  item("🫂", "people hugging", "people & body"),
  item("💚", "green heart", "smileys & emotion"),
  item("💔", "broken heart", "smileys & emotion"),
  item("👋", "waving hand", "people & body"),
  item("👑", "crown", "objects"),
  item("😈", "smiling face with horns", "smileys & emotion"),
  item("💸", "money with wings", "objects"),
  item("🔗", "link", "objects"),
  item("❄️", "snowflake", "travel & places"),
  item("❤️‍🔥", "heart on fire", "smileys & emotion"),
  item("📅", "calendar", "objects"),
  item("💰", "money bag", "objects"),
  item("🌟", "glowing star", "travel & places"),
  item("💬", "speech balloon", "smileys & emotion"),
  item("💖", "sparkling heart", "smileys & emotion"),
  item("🖤", "black heart", "smileys & emotion"),
  item("📷", "camera", "objects"),
  item("😏", "smirking face", "smileys & emotion"),
  item("💜", "purple heart", "smileys & emotion"),
  item("⚡", "high voltage", "travel & places"),
  item("🏆", "trophy", "activities"),
  item("🤭", "face with hand over mouth", "smileys & emotion"),
  item("🗿", "moai", "objects"),
  item("🫵", "index pointing at the viewer", "people & body"),
  item("🗣️", "speaking head", "people & body"),
  item("🤝", "handshake", "people & body"),
  item("💗", "growing heart", "smileys & emotion"),
  item("🙂", "slightly smiling face", "smileys & emotion"),
  item("🥀", "wilted flower", "animals & nature"),
  item("💛", "yellow heart", "smileys & emotion"),
  item("😋", "face savoring food", "smileys & emotion"),
  item("🫩", "face with bags under eyes", "smileys & emotion"),
  item("🤓", "nerd face", "smileys & emotion"),
  item("🥵", "hot face", "smileys & emotion"),
  item("🟢", "green circle", "symbols"),
  item("🫣", "face with peeking eye", "smileys & emotion"),
  item("🎃", "jack-o-lantern", "activities"),
  item("📚", "books", "objects"),
  item("☕", "hot beverage", "food & drink"),
  item("🥲", "smiling face with tear", "smileys & emotion"),
  item("💥", "collision", "smileys & emotion"),
  item("😄", "grinning face with smiling eyes", "smileys & emotion"),
  item("😱", "face screaming in fear", "smileys & emotion"),
  item("😀", "grinning face", "smileys & emotion"),
  item("🤖", "robot", "smileys & emotion"),
  item("📌", "pushpin", "objects"),
  item("🧿", "nazar amulet", "objects"),
  item("😆", "grinning squinting face", "smileys & emotion"),
  item("🙌", "raising hands", "people & body"),
  item("✈️", "airplane", "travel & places"),
  item("👏", "clapping hands", "people & body"),
  item("💯", "hundred points", "smileys & emotion"),
  item("🎀", "ribbon", "activities"),
  item("❗", "red exclamation mark", "symbols"),
  item("📝", "memo", "objects"),
  item("📢", "loudspeaker", "objects"),
  item("🌸", "cherry blossom", "animals & nature"),
  item("📈", "chart increasing", "objects"),
  item("📖", "open book", "objects"),
  item("🤯", "exploding head", "smileys & emotion"),
  item("💕", "two hearts", "smileys & emotion"),
  item("🙄", "face with rolling eyes", "smileys & emotion"),
  item("🧡", "orange heart", "smileys & emotion"),
  item("📱", "mobile phone", "objects"),
  item("🎅", "Santa Claus", "people & body"),
  item("🤗", "smiling face with open hands", "smileys & emotion"),
  item("📞", "telephone receiver", "objects"),
  item("🛒", "shopping cart", "objects"),
  item("😇", "smiling face with halo", "smileys & emotion"),
  item("🏠", "house", "travel & places"),
  item("👻", "ghost", "smileys & emotion"),
  item("🩵", "light blue heart", "smileys & emotion"),
  item("🎥", "movie camera", "objects"),
  item("🎨", "artist palette", "activities"),
  item("🎵", "musical note", "objects"),
  item("💻", "laptop", "objects"),
  item("💎", "gem stone", "objects"),
  item("⏰", "alarm clock", "travel & places"),
  item("🧠", "brain", "people & body"),
  item("🐾", "paw prints", "animals & nature"),
  item("‼️", "double exclamation mark", "symbols"),
  item("😮‍💨", "face exhaling", "smileys & emotion"),
  item("🖕", "middle finger", "people & body"),
  item("🌊", "water wave", "travel & places"),
  item("❓", "red question mark", "symbols"),
  item("🤫", "shushing face", "smileys & emotion"),
  item("😳", "flushed face", "smileys & emotion"),
  item("🤑", "money-mouth face", "smileys & emotion"),
  item("🎶", "musical notes", "objects"),
  item("🎂", "birthday cake", "food & drink"),
  item("🫀", "anatomical heart", "people & body"),
  item("📣", "megaphone", "objects"),
  item("🎮", "video game", "activities"),
  item("🤡", "clown face", "smileys & emotion"),
  item("⚽", "soccer ball", "activities"),
  item("🎯", "bullseye", "activities"),
  item("🤤", "drooling face", "smileys & emotion"),
  item("🚗", "automobile", "travel & places"),
  item("💩", "pile of poo", "smileys & emotion"),
  item("📸", "camera with flash", "objects"),
  item("💦", "sweat droplets", "smileys & emotion"),
  item("🥂", "clinking glasses", "food & drink"),
  item("🌐", "globe with meridians", "travel & places"),
  item("😡", "enraged face", "smileys & emotion"),
  item("🤨", "face with raised eyebrow", "smileys & emotion"),
  item("🔫", "water pistol", "activities"),
  item("🌎", "globe showing Americas", "travel & places"),
  item("📧", "e-mail", "objects"),
  item("💋", "kiss mark", "smileys & emotion"),
  item("☠️", "skull and crossbones", "smileys & emotion"),
  item("😃", "grinning face with big eyes", "smileys & emotion"),
  item("😌", "relieved face", "smileys & emotion"),
  item("🤪", "zany face", "smileys & emotion"),
  item("🌞", "sun with face", "travel & places"),
  item("🌒", "waxing crescent moon", "travel & places"),
  item("🎧", "headphone", "objects"),
  item("🤞", "crossed fingers", "people & body"),
  item("🟡", "yellow circle", "symbols"),
  item("🌱", "seedling", "animals & nature"),
  item("🫶🏼", "emoji", "emoji"),
  item("🙃", "upside-down face", "smileys & emotion"),
  item("🍂", "fallen leaf", "animals & nature"),
  item("🥶", "cold face", "smileys & emotion"),
  item("💍", "ring", "objects"),
  item("😬", "grimacing face", "smileys & emotion"),
  item("😢", "crying face", "smileys & emotion"),
  item("🎤", "microphone", "objects"),
  item("🐶", "dog face", "animals & nature"),
  item("😜", "winking face with tongue", "smileys & emotion"),
  item("🌹", "rose", "animals & nature"),
  item("✍️", "writing hand", "people & body"),
  item("✌️", "victory hand", "people & body"),
  item("✏️", "pencil", "objects"),
  item("⚔️", "crossed swords", "objects"),
  item("🫧", "bubbles", "objects"),
  item("🌈", "rainbow", "travel & places"),
  item("🍀", "four leaf clover", "animals & nature"),
  item("🙈", "see-no-evil monkey", "smileys & emotion"),
  item("😲", "astonished face", "smileys & emotion"),
  item("🌿", "herb", "animals & nature"),
  item("⚙️", "gear", "objects"),
  item("🔵", "blue circle", "symbols"),
  item("🙂‍↕️", "head shaking vertically", "smileys & emotion"),
  item("1️⃣", "keycap 1", "symbols"),
  item("🥇", "1st place medal", "activities"),
  item("🔔", "bell", "objects"),
  item("💭", "thought balloon", "smileys & emotion"),
  item("🩸", "drop of blood", "objects"),
  item("👌", "OK hand", "people & body"),
  item("📦", "package", "objects"),
  item("💫", "dizzy", "smileys & emotion"),
  item("💌", "love letter", "smileys & emotion"),
  item("📺", "television", "objects"),
  item("🪄", "magic wand", "activities"),
  item("⚕️", "medical symbol", "symbols"),
  item("🔊", "speaker high volume", "objects"),
  item("😝", "squinting face with tongue", "smileys & emotion"),
  item("🪩", "mirror ball", "activities"),
  item("🔒", "locked", "objects"),
  item("🛍️", "shopping bags", "objects"),
  item("🧸", "teddy bear", "activities"),
  item("🌴", "palm tree", "animals & nature"),
  item("😴", "sleeping face", "smileys & emotion"),
  item("ℹ️", "information", "symbols"),
  item("😛", "face with tongue", "smileys & emotion"),
  item("🌙", "crescent moon", "travel & places"),
  item("💅", "nail polish", "people & body"),
  item("🦋", "butterfly", "animals & nature"),
  item("📜", "scroll", "objects"),
  item("🚬", "cigarette", "objects"),
  item("🤌", "pinched fingers", "people & body"),
  item("🖥️", "desktop computer", "objects"),
  item("☑️", "check box with check", "symbols"),
  item("🔎", "magnifying glass tilted right", "objects"),
  item("☝️", "index pointing up", "people & body"),
  item("🫰", "hand with index finger and thumb crossed", "people & body"),
  item("🎆", "fireworks", "activities"),
  item("🎓", "graduation cap", "objects"),
  item("🎟️", "admission tickets", "activities"),
  item("🔍", "magnifying glass tilted left", "objects"),
  item("▶️", "play button", "symbols"),
  item("🦅", "eagle", "animals & nature"),
  item("💞", "revolving hearts", "smileys & emotion"),
  item("😩", "weary face", "smileys & emotion"),
  item("📲", "mobile phone with arrow", "objects"),
  item("📋", "clipboard", "objects"),
  item("🔱", "trident emblem", "symbols"),
  item("🎫", "ticket", "activities"),
  item("🗓️", "spiral calendar", "objects"),
  item("🚫", "prohibited", "symbols"),
  item("🌻", "sunflower", "animals & nature"),
  item("⬆️", "up arrow", "symbols"),
  item("2️⃣", "keycap 2", "symbols"),
  item("♾️", "infinity", "symbols"),
  item("🍕", "pizza", "food & drink"),
  item("🚚", "delivery truck", "travel & places"),
  item("😒", "unamused face", "smileys & emotion"),
  item("🍎", "red apple", "food & drink"),
  item("🪽", "wing", "animals & nature"),
  item("😠", "angry face", "smileys & emotion"),
  item("😵‍💫", "face with spiral eyes", "smileys & emotion"),
  item("💃", "woman dancing", "people & body"),
  item("🏖️", "beach with umbrella", "travel & places"),
  item("📊", "bar chart", "objects"),
  item("👅", "tongue", "people & body"),
  item("🕊️", "dove", "animals & nature"),
  item("🌳", "deciduous tree", "animals & nature"),
  item("🍷", "wine glass", "food & drink"),
  item("😞", "disappointed face", "smileys & emotion"),
  item("🏡", "house with garden", "travel & places"),
  item("😨", "fearful face", "smileys & emotion"),
  item("🎭", "performing arts", "activities"),
  item("🥷", "ninja", "people & body"),
  item("🪷", "lotus", "animals & nature"),
  item("🍑", "peach", "food & drink"),
  item("💐", "bouquet", "animals & nature"),
  item("🖼️", "framed picture", "activities"),
  item("🍽️", "fork and knife with plate", "food & drink"),
  item("🤠", "cowboy hat face", "smileys & emotion"),
  item("💵", "dollar banknote", "objects"),
  item("👽", "alien", "smileys & emotion"),
  item("📰", "newspaper", "objects"),
  item("🛡️", "shield", "objects"),
  item("🧐", "face with monocle", "smileys & emotion"),
  item("🐈", "cat", "animals & nature"),
  item("💤", "ZZZ", "smileys & emotion"),
  item("🍔", "hamburger", "food & drink"),
  item("🐱", "cat face", "animals & nature"),
  item("☁️", "cloud", "travel & places"),
  item("💧", "droplet", "travel & places"),
  item("☎️", "telephone", "objects"),
  item("🎙️", "studio microphone", "objects"),
  item("🔑", "key", "objects"),
  item("🍁", "maple leaf", "animals & nature"),
  item("☃️", "snowman", "travel & places"),
  item("🎬", "clapper board", "objects"),
  item("🏀", "basketball", "activities"),
  item("🦃", "turkey", "animals & nature"),
  item("🛠️", "hammer and wrench", "objects"),
  item("🎈", "balloon", "activities"),
  item("🟠", "orange circle", "symbols"),
  item("🍆", "eggplant", "food & drink"),
  item("🤮", "face vomiting", "smileys & emotion"),
  item("😮", "face with open mouth", "smileys & emotion"),
  item("🫵🏻", "emoji", "emoji"),
  item("💝", "heart with ribbon", "smileys & emotion"),
  item("🗺️", "world map", "travel & places"),
  item("🌍", "globe showing Europe-Africa", "travel & places"),
  item("🎊", "confetti ball", "activities"),
  item("🍃", "leaf fluttering in wind", "animals & nature"),
  item("🍻", "clinking beer mugs", "food & drink"),
  item("🤎", "brown heart", "smileys & emotion"),
  item("🌷", "tulip", "animals & nature"),
  item("🐟", "fish", "animals & nature"),
  item("🎸", "guitar", "objects"),
  item("🥱", "yawning face", "smileys & emotion"),
  item("⚖️", "balance scale", "objects"),
  item("⏳", "hourglass not done", "travel & places"),
  item("😤", "face with steam from nose", "smileys & emotion"),
  item("🌼", "blossom", "animals & nature"),
  item("🐈‍⬛", "black cat", "animals & nature"),
  item("🍓", "strawberry", "food & drink"),
  item("3️⃣", "keycap 3", "symbols"),
  item("💼", "briefcase", "objects"),
  item("🔞", "no one under eighteen", "symbols"),
  item("🔮", "crystal ball", "activities"),
  item("🚧", "construction", "travel & places"),
  item("🕯️", "candle", "objects"),
  item("👁️", "eye", "people & body"),
  item("✉️", "envelope", "objects"),
  item("🏎️", "racing car", "travel & places"),
  item("🌲", "evergreen tree", "animals & nature"),
  item("🍫", "chocolate bar", "food & drink"),
  item("😐", "neutral face", "smileys & emotion"),
  item("🍿", "popcorn", "food & drink"),
  item("🐐", "goat", "animals & nature"),
  item("🤦", "person facepalming", "people & body"),
  item("🏃", "person running", "people & body"),
  item("👈", "backhand index pointing left", "people & body"),
  item("♥️", "heart suit", "activities"),
  item("💲", "heavy dollar sign", "symbols"),
  item("🐝", "honeybee", "animals & nature"),
  item("🤬", "face with symbols on mouth", "smileys & emotion"),
  item("💨", "dashing away", "smileys & emotion"),
  item("💘", "heart with arrow", "smileys & emotion"),
  item("🍪", "cookie", "food & drink"),
  item("🙂‍↔️", "head shaking horizontally", "smileys & emotion"),
  item("⌛", "hourglass done", "travel & places"),
  item("🐰", "rabbit face", "animals & nature"),
  item("🌘", "waning crescent moon", "travel & places"),
  item("🌔", "waxing gibbous moon", "travel & places"),
  item("⛰️", "mountain", "travel & places"),
  item("🌺", "hibiscus", "animals & nature"),
  item("🫶🏽", "emoji", "emoji"),
  item("🦇", "bat", "animals & nature"),
  item("🌶️", "hot pepper", "food & drink"),
  item("🐦", "bird", "animals & nature"),
  item("🎲", "game die", "activities"),
  item("🔪", "kitchen knife", "food & drink"),
  item("👾", "alien monster", "smileys & emotion"),
  item("🏈", "american football", "activities"),
  item("🟥", "red square", "symbols"),
  item("👎", "thumbs down", "people & body"),
  item("💣", "bomb", "objects"),
  item("🙏🏻", "emoji", "emoji"),
  item("🐺", "wolf", "animals & nature"),
  item("🪙", "coin", "objects"),
  item("🤷", "person shrugging", "people & body"),
  item("👹", "ogre", "smileys & emotion"),
  item("🐕", "dog", "animals & nature"),
  item("🛑", "stop sign", "travel & places"),
  item("🐉", "dragon", "animals & nature"),
  item("👶", "baby", "people & body"),
  item("💳", "credit card", "objects"),
  item("🧊", "ice", "food & drink"),
  item("🩶", "grey heart", "smileys & emotion"),
  item("🪫", "low battery", "objects"),
  item("🍺", "beer mug", "food & drink"),
  item("🍹", "tropical drink", "food & drink"),
  item("🍾", "bottle with popping cork", "food & drink"),
  item("🔹", "small blue diamond", "symbols"),
  item("☹️", "frowning face", "smileys & emotion"),
  item("😥", "sad but relieved face", "smileys & emotion"),
  item("🏢", "office building", "travel & places"),
  item("🦁", "lion", "animals & nature"),
  item("🔨", "hammer", "objects"),
  item("🍒", "cherries", "food & drink"),
  item("✂️", "scissors", "objects"),
  item("⚫", "black circle", "symbols"),
  item("🐻", "bear", "animals & nature"),
  item("🍌", "banana", "food & drink"),
  item("🏫", "school", "travel & places"),
  item("🥚", "egg", "food & drink"),
  item("🧪", "test tube", "objects"),
  item("😟", "worried face", "smileys & emotion"),
  item("😓", "downcast face with sweat", "smileys & emotion"),
  item("🟣", "purple circle", "symbols"),
  item("🕺", "man dancing", "people & body"),
  item("😰", "anxious face with sweat", "smileys & emotion"),
  item("📄", "page facing up", "objects"),
  item("💓", "beating heart", "smileys & emotion"),
  item("📹", "video camera", "objects"),
  item("🔋", "battery", "objects"),
  item("🥴", "woozy face", "smileys & emotion"),
  item("✝️", "latin cross", "symbols"),
  item("🐍", "snake", "animals & nature"),
  item("😚", "kissing face with closed eyes", "smileys & emotion"),
  item("🎰", "slot machine", "activities"),
  item("🪖", "military helmet", "objects"),
  item("💊", "pill", "objects"),
  item("😕", "confused face", "smileys & emotion"),
  item("🛏️", "bed", "objects"),
  item("🦌", "deer", "animals & nature"),
  item("🫨", "shaking face", "smileys & emotion"),
  item("🥊", "boxing glove", "activities"),
  item("➕", "plus", "symbols"),
  item("🌖", "waning gibbous moon", "travel & places"),
  item("⚪", "white circle", "symbols"),
  item("😫", "tired face", "smileys & emotion"),
  item("🩺", "stethoscope", "objects"),
  item("⏱️", "stopwatch", "travel & places"),
  item("😑", "expressionless face", "smileys & emotion"),
  item("🤘", "sign of the horns", "people & body"),
  item("😼", "cat with wry smile", "smileys & emotion"),
  item("🍰", "shortcake", "food & drink"),
  item("🍬", "candy", "food & drink"),
  item("🚌", "bus", "travel & places"),
  item("🌌", "milky way", "travel & places"),
  item("♻️", "recycling symbol", "symbols"),
  item("🌠", "shooting star", "travel & places"),
  item("📕", "closed book", "objects"),
  item("🍄", "mushroom", "animals & nature"),
  item("😻", "smiling cat with heart-eyes", "smileys & emotion"),
  item("😹", "cat with tears of joy", "smileys & emotion"),
  item("🧬", "dna", "objects"),
  item("👥", "busts in silhouette", "people & body"),
  item("🦊", "fox", "animals & nature"),
  item("🦖", "T-Rex", "animals & nature"),
  item("👊", "oncoming fist", "people & body"),
  item("📆", "tear-off calendar", "objects"),
  item("⚜️", "fleur-de-lis", "symbols"),
  item("🫢", "face with open eyes and hand over mouth", "smileys & emotion"),
  item("🦄", "unicorn", "animals & nature"),
  item("🍉", "watermelon", "food & drink"),
  item("🪐", "ringed planet", "travel & places"),
  item("🥁", "drum", "objects"),
  item("🪔", "diya lamp", "objects"),
  item("🐒", "monkey", "animals & nature"),
  item("🧀", "cheese wedge", "food & drink"),
  item("🏅", "sports medal", "activities"),
  item("🍊", "tangerine", "food & drink"),
  item("4️⃣", "keycap 4", "symbols"),
  item("📁", "file folder", "objects"),
  item("😶‍🌫️", "face in clouds", "smileys & emotion"),
  item("🐎", "horse", "animals & nature"),
  item("🧩", "puzzle piece", "activities"),
  item("🏝️", "desert island", "travel & places"),
  item("🐦‍🔥", "phoenix", "animals & nature"),
  item("💉", "syringe", "objects"),
  item("🍋", "lemon", "food & drink"),
  item("🍸", "cocktail glass", "food & drink"),
  item("🔧", "wrench", "objects"),
  item("🟩", "green square", "symbols"),
  item("🪦", "headstone", "objects"),
  item("🪬", "hamsa", "objects"),
  item("🐇", "rabbit", "animals & nature"),
  item("🙁", "slightly frowning face", "smileys & emotion"),
  item("👕", "t-shirt", "objects"),
  item("🗡️", "dagger", "objects"),
  item("🗳️", "ballot box with ballot", "objects"),
  item("📩", "envelope with arrow", "objects"),
  item("🪞", "mirror", "objects"),
  item("🆕", "NEW button", "symbols"),
  item("🌧️", "cloud with rain", "travel & places"),
  item("⁉️", "exclamation question mark", "symbols"),
  item("🕷️", "spider", "animals & nature"),
  item("🦴", "bone", "people & body"),
  item("🌕", "full moon", "travel & places"),
  item("🗑️", "wastebasket", "objects"),
  item("🧵", "thread", "activities"),
  item("👍🏻", "emoji", "emoji"),
  item("🍴", "fork and knife", "food & drink"),
  item("🐔", "chicken", "animals & nature"),
  item("🎞️", "film frames", "objects"),
  item("🥩", "cut of meat", "food & drink"),
  item("👤", "bust in silhouette", "people & body"),
  item("❣️", "heart exclamation", "smileys & emotion"),
  item("👟", "running shoe", "objects"),
  item("🦷", "tooth", "people & body"),
  item("🤢", "nauseated face", "smileys & emotion"),
  item("🌑", "new moon", "travel & places"),
  item("🐧", "penguin", "animals & nature"),
  item("🐸", "frog", "animals & nature"),
  item("⬅️", "left arrow", "symbols"),
  item("🌀", "cyclone", "travel & places"),
  item("📉", "chart decreasing", "objects"),
  item("🖊️", "pen", "objects"),
  item("🏰", "castle", "travel & places"),
  item("🍲", "pot of food", "food & drink"),
  item("⛔", "no entry", "symbols"),
  item("🍳", "cooking", "food & drink"),
  item("🎇", "sparkler", "activities"),
  item("🤏", "pinching hand", "people & body"),
  item("🍗", "poultry leg", "food & drink"),
  item("🪨", "rock", "travel & places"),
  item("🍦", "soft ice cream", "food & drink"),
  item("🖌️", "paintbrush", "objects"),
}

local insert_character = function(char, started_in_insert)
  local mode = vim.api.nvim_get_mode().mode:sub(1, 1)

  if started_in_insert and mode ~= "i" then
    local keys = vim.api.nvim_replace_termcodes("a" .. char, true, false, true)
    vim.api.nvim_feedkeys(keys, "n", true)
    return
  end

  vim.api.nvim_put({ char }, "c", true, true)
end

local pick_and_insert = function(items, prompt)
  local started_in_insert = vim.api.nvim_get_mode().mode:sub(1, 1) == "i"

  vim.ui.select(items, {
    prompt = prompt,
    format_item = function(entry)
      return entry.label
    end,
  }, function(selection)
    if not selection then return end
    vim.schedule(function()
      insert_character(selection.char, started_in_insert)
    end)
  end)
end

local insert_unicode = function()
  pick_and_insert(unicode_items, "Insert unicode")
end

local insert_emoji = function()
  pick_and_insert(emoji_items, "Insert emoji")
end

local insert_char_prefix = function()
  local ok, key = pcall(vim.fn.getcharstr)
  if not ok or not key or key == "" then return end

  local ctrl_v = vim.api.nvim_replace_termcodes("<C-v>", true, false, true)

  if key == "v" or key == "V" or key == ctrl_v then
    insert_unicode()
    return
  end

  if key == "e" or key == "E" then
    insert_emoji()
    return
  end

  local fallback_keys = vim.api.nvim_replace_termcodes("<C-v>" .. key, true, false, true)
  vim.api.nvim_feedkeys(fallback_keys, "n", true)
end

local insert_char = function(opts)
  local mode = vim.trim((opts and opts.args) or "")
  if mode == "" or mode == "unicode" then
    insert_unicode()
    return
  end
  if mode == "emoji" then
    insert_emoji()
    return
  end
  vim.notify("InsertChar supports: unicode | emoji", vim.log.levels.WARN)
end

return lib.module.create({
  name = "workflow/char-picker",
  hosts = "*",
  setup = function()
    vim.api.nvim_create_user_command("InsertUnicode", insert_unicode, { desc = "Insert Unicode character" })
    vim.api.nvim_create_user_command("InsertEmoji", insert_emoji, { desc = "Insert emoji" })
    vim.api.nvim_create_user_command("InsertChar", insert_char, {
      nargs = "?",
      desc = "Insert character from unicode or emoji picker",
      complete = function()
        return { "unicode", "emoji" }
      end,
    })
  end,
  mappings = {
    { "i", "<C-v>", insert_char_prefix, "Character picker prefix: v=unicode e=emoji" },
    { "n", "<leader>iu", insert_unicode, "Insert Unicode character" },
    { "n", "<leader>ie", insert_emoji, "Insert emoji" },
  },
  exports = {
    insert_unicode = insert_unicode,
    insert_emoji = insert_emoji,
  },
})
