local colors = {
  -- PATCH_OPEN
Normal = {fg = "#CDCFE4", bg = "#23242F"},
["@text"] = {link = "Normal"},
["@text.literal.markdown"] = {link = "Normal"},
Boolean = {fg = "#E87DC4"},
["@boolean"] = {link = "Boolean"},
Character = {fg = "#A8C76B"},
["@character"] = {link = "Character"},
CmpItemAbbr = {fg = "#CDCFE4"},
CmpItemAbbrDeprecated = {fg = "#6F7295", strikethrough = true},
CmpItemAbbrMatch = {fg = "#4DB5FF"},
CmpItemAbbrMatchFuzzy = {fg = "#4DB5FF", bold = true},
CmpItemKind = {fg = "#4DB5FF"},
CmpItemKindClass = {fg = "#69BCF7"},
CmpItemKindColor = {},
CmpItemKindConstant = {fg = "#BDC0E0"},
CmpItemKindConstructor = {fg = "#69BCF7"},
CmpItemKindCopilot = {fg = "#E87DC4"},
CmpItemKindEnum = {fg = "#26CAD9"},
CmpItemKindEnumMember = {fg = "#26CAD9"},
CmpItemKindEvent = {fg = "#26CAD9"},
CmpItemKindField = {fg = "#B3B6D6"},
CmpItemKindFile = {fg = "#4DB5FF"},
CmpItemKindFolder = {fg = "#4DB5FF"},
CmpItemKindFunction = {fg = "#4DB5FF"},
CmpItemKindInterface = {fg = "#26CAD9"},
CmpItemKindKeyword = {fg = "#BB81E4"},
CmpItemKindMethod = {fg = "#4DB5FF"},
CmpItemKindModule = {fg = "#F2BF5A"},
CmpItemKindOperator = {fg = "#8185B1"},
CmpItemKindProperty = {fg = "#B3B6D6"},
CmpItemKindReference = {},
CmpItemKindSnippet = {},
CmpItemKindStruct = {fg = "#26CAD9"},
CmpItemKindText = {fg = "#CDCFE4"},
CmpItemKindTypeParameter = {fg = "#26CAD9"},
CmpItemKindUnit = {fg = "#26CAD9"},
CmpItemKindValue = {fg = "#E87DC4"},
CmpItemKindVariable = {fg = "#BDC0E0"},
CmpItemMenu = {fg = "#6F7295"},
ColorColumn = {},
Comment = {fg = "#6F7295", italic = true},
SpecialComment = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@text.todo.checked"] = {link = "Comment"},
Conceal = {fg = "#B3B6D6"},
Conditional = {fg = "#BB81E4"},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#BDC0E0"},
["@constant"] = {link = "Constant"},
["@text.reference"] = {link = "Constant"},
Constructor = {fg = "#69BCF7"},
["@constructor"] = {link = "Constructor"},
Cursor = {fg = "#23242F", bg = "#CDCFE4"},
CursorColumn = {},
CursorIM = {},
CursorLine = {bg = "#343646"},
CursorLineNr = {fg = "#8487A4", bg = "#343646"},
CursorLineSign = {fg = "#F67E55", bg = "#343646"},
Debug = {fg = "#E64C66"},
["@debug"] = {link = "Debug"},
["@constant.macro"] = {link = "Define"},
["@define"] = {link = "Define"},
Delimiter = {fg = "#6D7097"},
["@constructor.lua"] = {link = "Delimiter"},
["@punctuation"] = {link = "Delimiter"},
["@punctuation.bracket"] = {link = "Delimiter"},
["@punctuation.delimiter"] = {link = "Delimiter"},
["@punctuation.special"] = {link = "Delimiter"},
["@tag.delimiter"] = {link = "Delimiter"},
DiagnosticError = {fg = "#E64C66"},
DiagnosticFloatingError = {fg = "#E64C66"},
DiagnosticFloatingHint = {fg = "#26CAD9"},
DiagnosticFloatingInfo = {fg = "#4DB5FF"},
DiagnosticFloatingWarn = {fg = "#F67E55"},
DiagnosticHint = {fg = "#26CAD9"},
DiagnosticInfo = {fg = "#4DB5FF"},
DiagnosticSignError = {fg = "#E64C66"},
DiagnosticSignHint = {fg = "#26CAD9"},
DiagnosticSignInfo = {fg = "#4DB5FF"},
DiagnosticSignWarn = {fg = "#F67E55"},
DiagnosticUnderlineError = {undercurl = true},
DiagnosticUnderlineHint = {undercurl = true},
DiagnosticUnderlineInfo = {undercurl = true},
DiagnosticUnderlineWarn = {undercurl = true},
DiagnosticUnnecessary = {undercurl = true},
DiagnosticVirtualTextError = {fg = "#E64C66"},
DiagnosticVirtualTextHint = {fg = "#26CAD9"},
DiagnosticVirtualTextInfo = {fg = "#4DB5FF"},
DiagnosticVirtualTextWarn = {fg = "#BD370A"},
DiagnosticWarn = {fg = "#F67E55"},
DiffAdd = {fg = "#A8C76B"},
diffAdded = {link = "DiffAdd"},
DiffChange = {fg = "#F2BF5A"},
diffChanged = {link = "DiffChange"},
DiffDelete = {fg = "#E64C66"},
diffRemoved = {link = "DiffDelete"},
DiffText = {fg = "#4DB5FF"},
Directory = {fg = "#4DB5FF"},
EndOfBuffer = {fg = "#23242F"},
Error = {fg = "#E64C66"},
["@error"] = {link = "Error"},
ErrorMsg = {fg = "#EB4763"},
["@text.danger"] = {link = "ErrorMsg"},
Exception = {fg = "#D65C85"},
["@exception"] = {link = "Exception"},
Field = {fg = "#B3B6D6"},
["@field"] = {link = "Field"},
["@float"] = {link = "Float"},
FoldColumn = {},
Folded = {},
Function = {fg = "#4DB5FF"},
["@function"] = {link = "Function"},
["@function.call"] = {link = "Function"},
["@method"] = {link = "Function"},
["@method.call"] = {link = "Function"},
["@namespace"] = {link = "Function"},
GitSignsAdd = {fg = "#8DB143"},
GitSignsAddPreview = {},
GitSignsChange = {fg = "#EDA71D"},
GitSignsDelete = {fg = "#D61F3D"},
GitSignsDeletePreview = {},
Identifier = {fg = "#BDC0E0"},
["@lsp.type.identifier"] = {link = "Identifier"},
["@symbol"] = {link = "Identifier"},
["@tag.attribute"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
IncSearch = {fg = "#23242F", bg = "#F2BF5A"},
["@include"] = {link = "Include"},
IndentBlanklineIndent1 = {fg = "#4C4E61"},
IndentBlanklineIndent2 = {fg = "#464759"},
IndentBlanklineIndent3 = {fg = "#414353"},
IndentBlanklineIndent4 = {fg = "#3A3C4A"},
IndentBlanklineIndent5 = {fg = "#363745"},
IndentBlanklineIndent6 = {fg = "#2F303C"},
Keyword = {fg = "#BB81E4"},
["@keyword"] = {link = "Keyword"},
["@keyword.function"] = {link = "Keyword"},
Label = {fg = "#BB81E4"},
["@label"] = {link = "Label"},
LineNr = {fg = "#484A61"},
LspCodeLens = {fg = "#9599C6"},
LspCodeLensSeparator = {fg = "#5D63A8"},
LspReferenceRead = {bg = "#EDA71D"},
LspReferenceText = {bg = "#9599C6"},
LspReferenceWrite = {bg = "#D61F3D"},
LspSignatureActiveParameter = {fg = "#4DB5FF"},
Macro = {fg = "#CF6399"},
["@function.macro"] = {link = "Macro"},
["@keyword.operator"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
["@text.environment"] = {link = "Macro"},
MatchParen = {bg = "#484A61"},
NonText = {fg = "#9599C6"},
NormalFloat = {},
NormalNC = {},
Number = {fg = "#E87DC4"},
Float = {link = "Number"},
["@number"] = {link = "Number"},
NvimTreeFolderIcon = {fg = "#2EA8FF"},
NvimTreeFolderName = {fg = "#CDCFE4"},
NvimTreeGitDeleted = {fg = "#E64C66"},
NvimTreeGitDirty = {fg = "#F67E55"},
NvimTreeGitNew = {fg = "#A8C76B"},
NvimTreeImageFile = {},
NvimTreeIndentMarker = {fg = "#646787"},
NvimTreeNormal = {bg = "#272835"},
NvimTreeNormalNC = {},
NvimTreeOpenedFile = {fg = "#4DB5FF"},
NvimTreeRootFolder = {fg = "#4DB5FF", bold = true},
NvimTreeSpecialFile = {fg = "#4DB5FF"},
NvimTreeSymlink = {},
NvimTreeWinSeparator = {fg = "#383A4C", bg = "#272835"},
Operator = {fg = "#8185B1"},
["@operator"] = {link = "Operator"},
Parameter = {fg = "#DAA63E"},
["@parameter"] = {link = "Parameter"},
Pmenu = {fg = "#CDCFE4", bg = "#343646"},
PmenuSbar = {bg = "#484A61"},
PmenuSel = {fg = "#23242F", bg = "#4DB5FF"},
PmenuThumb = {bg = "#6C7093"},
PreProc = {fg = "#BB81E4"},
["@attribute"] = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Property = {fg = "#B3B6D6"},
["@property"] = {link = "Property"},
RainbowBlue = {fg = "#4B85AF"},
RainbowCyan = {fg = "#46787C"},
RainbowGreen = {fg = "#7A875E"},
RainbowOrange = {fg = "#AA6650"},
RainbowRed = {fg = "#95505C"},
RainbowViolet = {fg = "#AE6194"},
RainbowYellow = {fg = "#A78B52"},
Repeat = {fg = "#BB81E4"},
["@repeat"] = {link = "Repeat"},
Search = {fg = "#23242F", bg = "#EDA71D"},
Substitute = {link = "Search"},
SignColumn = {},
Special = {fg = "#F67E55"},
SpecialChar = {link = "Special"},
Tag = {link = "Special"},
["@text.literal.markdown_inline"] = {link = "Special"},
["@text.math"] = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
["@text.note"] = {link = "SpecialComment"},
SpecialKeyword = {fg = "#BB81E4"},
Define = {link = "SpecialKeyword"},
Include = {link = "SpecialKeyword"},
PreCondit = {link = "SpecialKeyword"},
["@keyword.coroutine"] = {link = "SpecialKeyword"},
Statement = {fg = "#BB81E4"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#A8C76B"},
["@string"] = {link = "String"},
["@string.regex"] = {link = "String"},
["@text.literal"] = {link = "String"},
["@structure"] = {link = "Structure"},
["@tag"] = {link = "Tag"},
TermCursor = {},
TermCursorNC = {},
Title = {fg = "#F075C7"},
["@text.title"] = {link = "Title"},
Todo = {fg = "#F2BF5A", bold = true, italic = true},
["@text.todo"] = {link = "Todo"},
["@text.todo.unchecked"] = {link = "Todo"},
Type = {fg = "#26CAD9"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@text.environment.name"] = {link = "Type"},
["@type"] = {link = "Type"},
["@type.qualifier"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {undercurl = true},
["@text.underline"] = {link = "Underlined"},
["@text.uri"] = {link = "Underlined"},
VertSplit = {fg = "#343646"},
Visual = {bg = "#484A61"},
WarningMsg = {},
["@text.warning"] = {link = "WarningMsg"},
Whitespace = {fg = "#7B7C8A"},
SpecialKey = {link = "Whitespace"},
lCursor = {},
["@lsp.typemod.deriveHelper.attribute"] = {link = "@attribute"},
["@constant.builtin"] = {link = "@boolean"},
["@lsp.type.boolean"] = {link = "@boolean"},
["@builtin"] = {fg = "#D65C85"},
["@function.builtin"] = {link = "@builtin"},
["@keyword.return"] = {link = "@builtin"},
["@variable.builtin"] = {link = "@builtin"},
["@lsp.type.character"] = {link = "@character"},
["@lsp.mod.constant"] = {link = "@constant"},
["@lsp.type.enumMember"] = {link = "@constant"},
["@lsp.type.class"] = {link = "@constructor"},
["@lsp.typemod.property.declaration"] = {link = "@field"},
["@lsp.type.float"] = {link = "@float"},
["@lsp.typemod.class.defaultLibrary"] = {link = "@function.builtin"},
["@lsp.typemod.function.defaultLibrary"] = {link = "@function.builtin"},
["@constructor.tsx"] = {link = "@function"},
["@lsp.type.function"] = {link = "@function"},
["@lsp.type.interface"] = {link = "@keyword"},
["@lsp.type.keyword"] = {link = "@keyword"},
["@lsp.mod.readonly"] = {link = "@lsp.mod.constant"},
["@lsp.mod.static"] = {italic = true},
["@lsp.type.event"] = {fg = "#F67E55"},
["@lsp.typemod.function.readonly"] = {link = "@lsp.type.function"},
["@lsp.type.lifetime"] = {fg = "#E87DC4"},
["@lsp.typemod.type.readonly"] = {link = "@lsp.type.type"},
["@lsp.typemod.string.constant"] = {},
["@lsp.typemod.string.readonly"] = {},
["@lsp.typemod.string.static"] = {},
["@lsp.mod.annotation"] = {link = "@macro"},
["@lsp.type.macro"] = {link = "@macro"},
["@lsp.type.method"] = {link = "@method"},
["@lsp.type.namespace"] = {link = "@namespace"},
["@none"] = {fg = "NONE", bg = "NONE"},
["@lsp.type.number"] = {link = "@number"},
["@lsp.type.operator"] = {link = "@operator"},
["@lsp.type.decorator"] = {link = "@parameter"},
["@lsp.type.parameter"] = {link = "@parameter"},
["@lsp.type.property"] = {link = "@property"},
["@tag.attribute.tsx"] = {link = "@property"},
["@slang.banner"] = {fg = "#A9B9E5", bg = "#38425B"},
["@slang.bold"] = {fg = "#C1D1FF", bold = true},
["@slang.code_block_content"] = {fg = "#BDC7EE"},
["@slang.code_block_end"] = {fg = "#7378a5", italic = true},
["@slang.code_block_fence"] = {bg = "#2f3041"},
["@slang.code_block_language"] = {fg = "#6F75A9", italic = true},
["@slang.code_block_start"] = {fg = "#7378a5", italic = true},
["@slang.comment"] = {fg = "#6F7295"},
["@slang.date"] = {fg = "#FC824A"},
["@slang.daterange"] = {fg = "#FC824A"},
["@slang.datetime"] = {fg = "#FC824A"},
["@slang.datetimerange"] = {fg = "#FC824A"},
["@slang.document.meta"] = {fg = "#F2BF5A"},
["@slang.document.meta.field"] = {fg = "#F075C7"},
["@slang.document.meta.field.key"] = {fg = "#E87DC4"},
["@slang.document.title"] = {fg = "#F67E55", bold = true},
["@slang.error"] = {fg = "#ffffff", bg = "#7a2633"},
["@slang.external_link"] = {fg = "#5db4e3", italic = true, undercurl = true},
["@slang.heading_1.marker"] = {fg = "#9999FF"},
["@slang.heading_1.text"] = {fg = "#9999FF", bold = true},
["@slang.heading_2.marker"] = {fg = "#C08FFF"},
["@slang.heading_2.text"] = {fg = "#C08FFF", bold = true},
["@slang.heading_3.marker"] = {fg = "#E38FFF"},
["@slang.heading_3.text"] = {fg = "#E38FFF", bold = true},
["@slang.heading_4.marker"] = {fg = "#FFC78F"},
["@slang.heading_4.text"] = {fg = "#FFC78F", bold = true},
["@slang.heading_5.marker"] = {fg = "#04D3D0"},
["@slang.heading_5.text"] = {fg = "#04D3D0", bold = true},
["@slang.heading_6.marker"] = {fg = "#f0969f"},
["@slang.heading_6.text"] = {fg = "#f0969f", bold = true},
["@slang.heading_done"] = {fg = "#6F7295", bold = true},
["@slang.inline_code"] = {fg = "#F09070"},
["@slang.italic"] = {italic = true},
["@slang.label"] = {fg = "#F8CD77"},
["@slang.link"] = {fg = "#5BC0CD", italic = true, undercurl = true},
["@slang.list_item"] = {},
["@slang.list_item_label"] = {fg = "#F8CD77", italic = true},
["@slang.list_item_label_marker"] = {fg = "#6F7295"},
["@slang.list_item_marker"] = {fg = "#7B7C8A"},
["@slang.number"] = {fg = "#71c9f6"},
["@slang.section"] = {fg = "#04D3D0"},
["@slang.string"] = {fg = "#4efa8e"},
["@slang.tag.context"] = {fg = "#F2BF5A"},
["@slang.tag.danger"] = {fg = "#ffffff", bg = "#C3423F"},
["@slang.tag.hash"] = {fg = "#5BC0EB"},
["@slang.tag.identifier"] = {fg = "#e38fff"},
["@slang.tag.negative"] = {fg = "#FA4224"},
["@slang.tag.positive"] = {fg = "#9BC53D"},
["@slang.task_active"] = {fg = "#26CAD9"},
["@slang.task_cancelled"] = {fg = "#fa4040"},
["@slang.task_default"] = {},
["@slang.task_done"] = {fg = "#6F7295"},
["@slang.task_schedule"] = {fg = "#FF8000"},
["@slang.task_session"] = {fg = "#7378a5"},
["@slang.ticket"] = {fg = "#fa89f6"},
["@slang.time"] = {fg = "#FC824A"},
["@slang.timerange"] = {fg = "#FC824A"},
["@slang.underline"] = {underline = true},
["@lsp.mod.interpolation"] = {link = "@string.special"},
["@lsp.type.string"] = {link = "@string"},
["@lsp.type.struct"] = {link = "@structure"},
["@text.emphasis"] = {italic = true},
["@text.strike"] = {strikethrough = true},
["@text.strong"] = {bold = true},
["@lsp.type.typeAlias"] = {link = "@type.definition"},
["@lsp.type.enum"] = {link = "@type"},
["@lsp.type.type"] = {link = "@type"},
["@lsp.type.typeParameter"] = {link = "@type"},
["@lsp.typemod.interface"] = {link = "@type"},
["@lsp.typemod.type.defaultLibrary"] = {link = "@type"},
["@lsp.typemod.typeParameter"] = {link = "@type"},
["@type.builtin"] = {link = "@type"},
["@lsp.typemod.variable.defaultLibrary"] = {link = "@variable.builtin"},
["@lsp.type.variable"] = {link = "@variable"},
  -- PATCH_CLOSE
}

vim.opt.background = "dark"
vim.g.colors_name = "static"
vim.cmd.highlight("clear")
-- vim.cmd.syntax("reset")

for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
