local colors = {
  -- PATCH_OPEN
Normal = {fg = "#BAC2EE", bg = "#21222C"},
["@text"] = {link = "Normal"},
["@text.literal.markdown"] = {link = "Normal"},
Boolean = {fg = "#E085C2"},
["@boolean"] = {link = "Boolean"},
Character = {fg = "#99D65C"},
["@character"] = {link = "Character"},
CmpItemAbbr = {fg = "#BAC2EE"},
CmpItemAbbrDeprecated = {fg = "#6E77A6", strikethrough = true},
CmpItemAbbrMatch = {fg = "#38B9FA"},
CmpItemAbbrMatchFuzzy = {fg = "#38B9FA", bold = true},
CmpItemKind = {fg = "#38B9FA"},
CmpItemKindClass = {fg = "#54BEF2"},
CmpItemKindColor = {},
CmpItemKindConstant = {fg = "#E085C2"},
CmpItemKindConstructor = {fg = "#54BEF2"},
CmpItemKindCopilot = {fg = "#E085C2"},
CmpItemKindEnum = {fg = "#3CDDDD"},
CmpItemKindEnumMember = {fg = "#3CDDDD"},
CmpItemKindEvent = {fg = "#3CDDDD"},
CmpItemKindField = {fg = "#95A1DF"},
CmpItemKindFile = {fg = "#38B9FA"},
CmpItemKindFolder = {fg = "#38B9FA"},
CmpItemKindFunction = {fg = "#38B9FA"},
CmpItemKindInterface = {fg = "#3CDDDD"},
CmpItemKindKeyword = {fg = "#BF93EC"},
CmpItemKindMethod = {fg = "#38B9FA"},
CmpItemKindModule = {fg = "#EB9947"},
CmpItemKindOperator = {fg = "#6072C7"},
CmpItemKindProperty = {fg = "#95A1DF"},
CmpItemKindReference = {},
CmpItemKindSnippet = {fg = "#BF80FF"},
CmpItemKindStruct = {fg = "#3CDDDD"},
CmpItemKindText = {fg = "#BAC2EE"},
CmpItemKindTypeParameter = {fg = "#3CDDDD"},
CmpItemKindUnit = {fg = "#3CDDDD"},
CmpItemKindValue = {fg = "#E085C2"},
CmpItemKindVariable = {fg = "#BAC2EE"},
CmpItemMenu = {fg = "#6E77A6"},
ColorColumn = {},
Comment = {fg = "#6E77A6", italic = true},
SpecialComment = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@text.todo.checked"] = {link = "Comment"},
Conceal = {fg = "#99A6E6"},
Conditional = {fg = "#BF93EC"},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#E085C2"},
["@constant"] = {link = "Constant"},
["@text.reference"] = {link = "Constant"},
Constructor = {fg = "#54BEF2"},
["@constructor"] = {link = "Constructor"},
Cursor = {fg = "#21222C", bg = "#BAC2EE"},
CursorColumn = {},
CursorIM = {},
CursorLine = {bg = "#343746"},
CursorLineNr = {fg = "#8489A4", bg = "#343746"},
CursorLineSign = {fg = "#F67E55", bg = "#343746"},
Debug = {fg = "#D65C66"},
["@debug"] = {link = "Debug"},
["@constant.macro"] = {link = "Define"},
["@define"] = {link = "Define"},
Delimiter = {fg = "#656E9A"},
["@constructor.lua"] = {link = "Delimiter"},
["@punctuation"] = {link = "Delimiter"},
["@punctuation.bracket"] = {link = "Delimiter"},
["@punctuation.delimiter"] = {link = "Delimiter"},
["@punctuation.special"] = {link = "Delimiter"},
["@tag.delimiter"] = {link = "Delimiter"},
DiagnosticError = {fg = "#D65C66"},
DiagnosticFloatingError = {fg = "#D65C66"},
DiagnosticFloatingHint = {fg = "#3CDDDD"},
DiagnosticFloatingInfo = {fg = "#38B9FA"},
DiagnosticFloatingWarn = {fg = "#F67E55"},
DiagnosticHint = {fg = "#3CDDDD"},
DiagnosticInfo = {fg = "#38B9FA"},
DiagnosticSignError = {fg = "#D65C66"},
DiagnosticSignHint = {fg = "#3CDDDD"},
DiagnosticSignInfo = {fg = "#38B9FA"},
DiagnosticSignWarn = {fg = "#F67E55"},
DiagnosticUnderlineError = {undercurl = true},
DiagnosticUnderlineHint = {undercurl = true},
DiagnosticUnderlineInfo = {undercurl = true},
DiagnosticUnderlineWarn = {undercurl = true},
DiagnosticUnnecessary = {undercurl = true},
DiagnosticVirtualTextError = {fg = "#D65C66"},
DiagnosticVirtualTextHint = {fg = "#3CDDDD"},
DiagnosticVirtualTextInfo = {fg = "#38B9FA"},
DiagnosticVirtualTextWarn = {fg = "#BD370A"},
DiagnosticWarn = {fg = "#F67E55"},
DiffAdd = {fg = "#99D65C"},
diffAdded = {link = "DiffAdd"},
DiffChange = {fg = "#EB9947"},
diffChanged = {link = "DiffChange"},
DiffDelete = {fg = "#D65C66"},
diffRemoved = {link = "DiffDelete"},
DiffText = {fg = "#38B9FA"},
Directory = {fg = "#38B9FA"},
EndOfBuffer = {fg = "#21222C"},
Error = {fg = "#D65C66"},
["@error"] = {link = "Error"},
ErrorMsg = {fg = "#DE545F"},
["@text.danger"] = {link = "ErrorMsg"},
Exception = {fg = "#D65C66"},
["@exception"] = {link = "Exception"},
Field = {fg = "#95A1DF"},
["@field"] = {link = "Field"},
["@float"] = {link = "Float"},
FoldColumn = {},
Folded = {},
Function = {fg = "#38B9FA"},
["@function"] = {link = "Function"},
["@function.call"] = {link = "Function"},
["@method"] = {link = "Function"},
["@method.call"] = {link = "Function"},
["@namespace"] = {link = "Function"},
GitSignsAdd = {fg = "#7AC431"},
GitSignsAddPreview = {},
GitSignsChange = {fg = "#DC7A18"},
GitSignsDelete = {fg = "#C4313D"},
GitSignsDeletePreview = {},
Identifier = {fg = "#BAC2EE"},
["@lsp.type.identifier"] = {link = "Identifier"},
["@symbol"] = {link = "Identifier"},
["@tag.attribute"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
IncSearch = {fg = "#21222C", bg = "#EB9947"},
["@include"] = {link = "Include"},
IndentBlanklineIndent1 = {fg = "#4A4D5E"},
IndentBlanklineIndent2 = {fg = "#434656"},
IndentBlanklineIndent3 = {fg = "#3F4250"},
IndentBlanklineIndent4 = {fg = "#383B47"},
IndentBlanklineIndent5 = {fg = "#343642"},
IndentBlanklineIndent6 = {fg = "#2D2F39"},
Keyword = {fg = "#BF93EC"},
["@keyword"] = {link = "Keyword"},
["@keyword.function"] = {link = "Keyword"},
Label = {fg = "#BF93EC"},
["@label"] = {link = "Label"},
LineNr = {fg = "#45495E"},
LspCodeLens = {fg = "#7486DC"},
LspCodeLensSeparator = {fg = "#334DCC"},
LspReferenceRead = {bg = "#DC7A18"},
LspReferenceText = {bg = "#7486DC"},
LspReferenceWrite = {bg = "#C4313D"},
LspSignatureActiveParameter = {fg = "#38B9FA"},
Macro = {fg = "#BF93EC"},
["@function.macro"] = {link = "Macro"},
["@keyword.operator"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
["@text.environment"] = {link = "Macro"},
MatchParen = {bg = "#45495E"},
NonText = {fg = "#7486DC"},
NormalFloat = {},
NormalNC = {},
Number = {fg = "#E085C2"},
Float = {link = "Number"},
["@number"] = {link = "Number"},
NvimTreeFolderIcon = {fg = "#1AAFF9"},
NvimTreeFolderName = {fg = "#BAC2EE"},
NvimTreeGitDeleted = {fg = "#D65C66"},
NvimTreeGitDirty = {fg = "#F67E55"},
NvimTreeGitNew = {fg = "#99D65C"},
NvimTreeImageFile = {},
NvimTreeIndentMarker = {fg = "#5F699B"},
NvimTreeNormal = {bg = "#252732"},
NvimTreeNormalNC = {},
NvimTreeOpenedFile = {fg = "#38B9FA"},
NvimTreeRootFolder = {fg = "#38B9FA", bold = true},
NvimTreeSpecialFile = {fg = "#38B9FA"},
NvimTreeSymlink = {},
NvimTreeWinSeparator = {fg = "#343A55", bg = "#252732"},
Operator = {fg = "#6072C7"},
["@operator"] = {link = "Operator"},
Parameter = {fg = "#EB9947"},
["@parameter"] = {link = "Parameter"},
Pmenu = {fg = "#BAC2EE", bg = "#343746"},
PmenuSbar = {bg = "#45495E"},
PmenuSel = {fg = "#21222C", bg = "#38B9FA"},
PmenuThumb = {bg = "#6A7090"},
PreProc = {fg = "#BF93EC"},
["@attribute"] = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Property = {fg = "#95A1DF"},
["@property"] = {link = "Property"},
RainbowBlue = {fg = "#3592C0"},
RainbowCyan = {fg = "#419F9F"},
RainbowGreen = {fg = "#7AA64E"},
RainbowOrange = {fg = "#C76443"},
RainbowRed = {fg = "#A64E56"},
RainbowViolet = {fg = "#C559A1"},
RainbowYellow = {fg = "#B57A40"},
Repeat = {fg = "#BF93EC"},
["@repeat"] = {link = "Repeat"},
Search = {fg = "#21222C", bg = "#DC7A18"},
Substitute = {link = "Search"},
SignColumn = {},
Special = {fg = "#F67E55"},
SpecialChar = {link = "Special"},
Tag = {link = "Special"},
["@tag.attribute.tsx"] = {link = "Special"},
["@text.literal.markdown_inline"] = {link = "Special"},
["@text.math"] = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
["@text.note"] = {link = "SpecialComment"},
SpecialKeyword = {fg = "#BF93EC"},
Define = {link = "SpecialKeyword"},
Include = {link = "SpecialKeyword"},
PreCondit = {link = "SpecialKeyword"},
["@keyword.coroutine"] = {link = "SpecialKeyword"},
["@tag.tsx"] = {link = "SpecialKeyword"},
Statement = {fg = "#BF93EC"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#99D65C"},
["@string"] = {link = "String"},
["@string.regex"] = {link = "String"},
["@text.literal"] = {link = "String"},
["@structure"] = {link = "Structure"},
TabLine = {bg = "#3D4052"},
TabLineFill = {bg = "#343746"},
TabLineSel = {bg = "#45495E"},
["@tag"] = {link = "Tag"},
TermCursor = {},
TermCursorNC = {},
Title = {fg = "#F075C7"},
["@text.title"] = {link = "Title"},
Todo = {fg = "#EB9947", bold = true, italic = true},
["@text.todo"] = {link = "Todo"},
["@text.todo.unchecked"] = {link = "Todo"},
Type = {fg = "#3CDDDD"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@text.environment.name"] = {link = "Type"},
["@type"] = {link = "Type"},
["@type.qualifier"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {undercurl = true},
["@text.underline"] = {link = "Underlined"},
["@text.uri"] = {link = "Underlined"},
VertSplit = {fg = "#343746"},
Visual = {bg = "#45495E"},
WarningMsg = {},
["@text.warning"] = {link = "WarningMsg"},
Whitespace = {fg = "#70758F"},
SpecialKey = {link = "Whitespace"},
lCursor = {},
["@lsp.typemod.deriveHelper.attribute"] = {link = "@attribute"},
["@constant.builtin"] = {link = "@boolean"},
["@lsp.type.boolean"] = {link = "@boolean"},
["@variable.builtin"] = {link = "@boolean"},
["@builtin"] = {fg = "#D65C66"},
["@function.builtin"] = {link = "@builtin"},
["@keyword.return"] = {link = "@builtin"},
["@lsp.type.character"] = {link = "@character"},
["@lsp.type.enumMember"] = {link = "@constant"},
["@constructor.tsx"] = {},
["@lsp.type.class"] = {link = "@constructor"},
["@lsp.typemod.property.declaration"] = {link = "@field"},
["@lsp.type.float"] = {link = "@float"},
["@lsp.type.keyword"] = {link = "@keyword"},
["@lsp.mod.constant"] = {},
["@lsp.mod.readonly"] = {},
["@lsp.mod.static"] = {italic = true},
["@lsp.type.event"] = {fg = "#F67E55"},
["@lsp.type.function"] = {},
["@lsp.type.lifetime"] = {fg = "#E085C2"},
["@lsp.typemod.function"] = {},
["@lsp.typemod.string.constant"] = {},
["@lsp.typemod.string.readonly"] = {},
["@lsp.typemod.string.static"] = {},
["@lsp.mod.annotation"] = {link = "@macro"},
["@lsp.type.macro"] = {link = "@macro"},
["@lsp.typemod.class.defaultLibrary"] = {link = "@macro"},
["@lsp.typemod.function.defaultLibrary"] = {link = "@macro"},
["@lsp.typemod.variable.defaultLibrary"] = {link = "@macro"},
["@lsp.type.method"] = {link = "@method"},
["@lsp.type.namespace"] = {link = "@namespace"},
["@none"] = {fg = "NONE", bg = "NONE"},
["@lsp.type.number"] = {link = "@number"},
["@lsp.type.operator"] = {link = "@operator"},
["@lsp.type.decorator"] = {link = "@parameter"},
["@lsp.type.parameter"] = {link = "@parameter"},
["@lsp.type.property"] = {link = "@property"},
["@slang.banner"] = {fg = "#A9B9E5", bg = "#38425B"},
["@slang.bold"] = {fg = "#C1D1FF", bold = true},
["@slang.code_block_content"] = {fg = "#BAC2EE"},
["@slang.code_block_end"] = {fg = "#45495E", italic = true},
["@slang.code_block_fence"] = {bg = "#343746"},
["@slang.code_block_language"] = {fg = "#595E78", italic = true},
["@slang.code_block_start"] = {fg = "#45495E", italic = true},
["@slang.comment"] = {fg = "#6E77A6"},
["@slang.date"] = {fg = "#FC824A"},
["@slang.daterange"] = {fg = "#FC824A"},
["@slang.datetime"] = {fg = "#FC824A"},
["@slang.datetimerange"] = {fg = "#FC824A"},
["@slang.document.meta"] = {fg = "#EB9947"},
["@slang.document.meta.field"] = {fg = "#F075C7"},
["@slang.document.meta.field.key"] = {fg = "#E085C2"},
["@slang.document.title"] = {fg = "#F67E55", bold = true},
["@slang.error"] = {fg = "#ffffff", bg = "#7a2633"},
["@slang.external_link"] = {fg = "#5db4e3", italic = true, undercurl = true},
["@slang.heading_1.marker"] = {fg = "#9999FF"},
["@slang.heading_1.text"] = {fg = "#9999FF", bold = true},
["@slang.heading_2.marker"] = {fg = "#C08FFF"},
["@slang.heading_2.text"] = {fg = "#C08FFF", bold = true},
["@slang.heading_3.marker"] = {fg = "#E38FFF"},
["@slang.heading_3.text"] = {fg = "#E38FFF", bold = true},
["@slang.heading_4.marker"] = {fg = "#FFC78F"},
["@slang.heading_4.text"] = {fg = "#FFC78F", bold = true},
["@slang.heading_5.marker"] = {fg = "#04D3D0"},
["@slang.heading_5.text"] = {fg = "#04D3D0", bold = true},
["@slang.heading_6.marker"] = {fg = "#f0969f"},
["@slang.heading_6.text"] = {fg = "#f0969f", bold = true},
["@slang.heading_done"] = {fg = "#6E77A6", bold = true},
["@slang.image"] = {fg = "#EB9947"},
["@slang.inline_code"] = {fg = "#F09070"},
["@slang.internal_link"] = {fg = "#5BC0CD", undercurl = true},
["@slang.italic"] = {italic = true},
["@slang.label"] = {fg = "#EB9947"},
["@slang.link"] = {fg = "#5BC0CD", italic = true, undercurl = true},
["@slang.list_item"] = {},
["@slang.list_item_label"] = {fg = "#F4AD67", italic = true},
["@slang.list_item_label_marker"] = {fg = "#6E77A6"},
["@slang.list_item_marker"] = {fg = "#70758F"},
["@slang.number"] = {fg = "#71c9f6"},
["@slang.section"] = {fg = "#04D3D0"},
["@slang.string"] = {fg = "#4efa8e"},
["@slang.tag.context"] = {fg = "#EB9947"},
["@slang.tag.danger"] = {fg = "#ffffff", bg = "#C3423F"},
["@slang.tag.hash"] = {fg = "#5BC0EB"},
["@slang.tag.identifier"] = {fg = "#e38fff"},
["@slang.tag.negative"] = {fg = "#FA4224"},
["@slang.tag.positive"] = {fg = "#9BC53D"},
["@slang.task_active"] = {fg = "#3CDDDD"},
["@slang.task_cancelled"] = {fg = "#fa4040"},
["@slang.task_default"] = {},
["@slang.task_done"] = {fg = "#6E77A6"},
["@slang.task_marker_default"] = {fg = "#6E77A6"},
["@slang.task_schedule"] = {fg = "#7378a5"},
["@slang.task_session"] = {fg = "#7378a5"},
["@slang.ticket"] = {fg = "#fa89f6"},
["@slang.time"] = {fg = "#FC824A"},
["@slang.timerange"] = {fg = "#FC824A"},
["@slang.underline"] = {underline = true},
["@lsp.mod.interpolation"] = {link = "@string.special"},
["@lsp.type.string"] = {link = "@string"},
["@lsp.type.struct"] = {link = "@structure"},
["@text.emphasis"] = {italic = true},
["@text.literal.syslang"] = {fg = "#BAC2EE"},
["@text.strike"] = {strikethrough = true},
["@text.strong"] = {bold = true},
["@lsp.type.typeAlias"] = {link = "@type.definition"},
["@lsp.type.enum"] = {link = "@type"},
["@lsp.type.interface"] = {link = "@type"},
["@lsp.type.type"] = {link = "@type"},
["@lsp.type.typeParameter"] = {link = "@type"},
["@lsp.typemod.interface"] = {link = "@type"},
["@lsp.typemod.type.defaultLibrary"] = {link = "@type"},
["@lsp.typemod.type.readonly"] = {link = "@type"},
["@lsp.typemod.typeParameter"] = {link = "@type"},
["@type.builtin"] = {link = "@type"},
["@lsp.type.variable"] = {link = "@variable"},
  -- PATCH_CLOSE
}

vim.opt.background = "dark"
vim.g.colors_name = "static"
vim.cmd.highlight("clear")
-- vim.cmd.syntax("reset")

for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
