local colors = {
  -- PATCH_OPEN
Normal = {fg = "#C2C9F0", bg = "#21222C"},
Boolean = {fg = "#3DB8F5"},
["@boolean"] = {link = "Boolean"},
Character = {fg = "#AACC66"},
["@character"] = {link = "Character"},
CmpItemAbbr = {fg = "#C2C9F0"},
CmpItemAbbrDeprecated = {fg = "#757DA3", strikethrough = true},
CmpItemAbbrMatch = {fg = "#3DB8F5"},
CmpItemAbbrMatchFuzzy = {fg = "#3DB8F5", bold = true},
CmpItemKind = {fg = "#3DB8F5"},
CmpItemKindClass = {fg = "#3DB8F5"},
CmpItemKindColor = {},
CmpItemKindConstant = {fg = "#52E0E0"},
CmpItemKindConstructor = {fg = "#52E0E0"},
CmpItemKindCopilot = {fg = "#F075B3"},
CmpItemKindEnum = {fg = "#52E0E0"},
CmpItemKindEnumMember = {fg = "#52E0E0"},
CmpItemKindEvent = {fg = "#F0B642"},
CmpItemKindField = {fg = "#FA9938"},
CmpItemKindFile = {fg = "#3DB8F5"},
CmpItemKindFolder = {fg = "#3DB8F5"},
CmpItemKindFunction = {fg = "#3DB8F5"},
CmpItemKindInterface = {fg = "#52E0E0"},
CmpItemKindKeyword = {fg = "#E6594C"},
CmpItemKindMethod = {fg = "#3DB8F5"},
CmpItemKindModule = {fg = "#F0B642"},
CmpItemKindOperator = {fg = "#C2C9F0"},
CmpItemKindProperty = {fg = "#FA9938"},
CmpItemKindReference = {},
CmpItemKindSnippet = {},
CmpItemKindStruct = {fg = "#52E0E0"},
CmpItemKindText = {fg = "#C2C9F0"},
CmpItemKindTypeParameter = {},
CmpItemKindUnit = {fg = "#52E0E0"},
CmpItemKindValue = {},
CmpItemKindVariable = {fg = "#C2C9F0"},
CmpItemMenu = {fg = "#757DA3"},
ColorColumn = {},
Comment = {fg = "#757DA3"},
SpecialComment = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
Conceal = {fg = "#A1ADE8"},
Conditional = {fg = "#D291F3"},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#3DB8F5"},
["@constant"] = {link = "Constant"},
Constructor = {fg = "#E29D12"},
["@constructor"] = {link = "Constructor"},
Cursor = {fg = "#21222C", bg = "#C2C9F0"},
CursorColumn = {},
CursorIM = {},
CursorLine = {bg = "#343746"},
CursorLineNr = {fg = "#8489A4", bg = "#343746"},
CursorLineSign = {fg = "#FA9938", bg = "#343746"},
Debug = {fg = "#E6594C"},
["@debug"] = {link = "Debug"},
["@define"] = {link = "Define"},
Delimiter = {fg = "#6A75AF"},
["@punctuation"] = {link = "Delimiter"},
["@punctuation.bracket"] = {link = "Delimiter"},
DiagnosticError = {fg = "#E6594C"},
DiagnosticFloatingError = {fg = "#E6594C"},
DiagnosticFloatingHint = {fg = "#52E0E0"},
DiagnosticFloatingInfo = {fg = "#3DB8F5"},
DiagnosticFloatingWarn = {fg = "#FA9938"},
DiagnosticHint = {fg = "#52E0E0"},
DiagnosticInfo = {fg = "#3DB8F5"},
DiagnosticSignError = {fg = "#E6594C"},
DiagnosticSignHint = {fg = "#52E0E0"},
DiagnosticSignInfo = {fg = "#3DB8F5"},
DiagnosticSignWarn = {fg = "#FA9938"},
DiagnosticUnderlineError = {sp = "#E6594C", undercurl = true},
DiagnosticUnderlineHint = {sp = "#52E0E0", undercurl = true},
DiagnosticUnderlineInfo = {sp = "#3DB8F5", undercurl = true},
DiagnosticUnderlineWarn = {sp = "#FA9938", undercurl = true},
DiagnosticVirtualTextError = {fg = "#E6594C"},
DiagnosticVirtualTextHint = {fg = "#52E0E0"},
DiagnosticVirtualTextInfo = {fg = "#3DB8F5"},
DiagnosticVirtualTextWarn = {fg = "#B35C05"},
DiagnosticWarn = {fg = "#FA9938"},
DiffAdd = {fg = "#AACC66"},
diffAdded = {link = "DiffAdd"},
DiffChange = {fg = "#F0B642"},
diffChanged = {link = "DiffChange"},
DiffDelete = {fg = "#E6594C"},
diffRemoved = {link = "DiffDelete"},
DiffText = {fg = "#3DB8F5"},
Directory = {fg = "#3DB8F5"},
EndOfBuffer = {fg = "#21222C"},
Error = {fg = "#E6594C"},
ErrorMsg = {fg = "#EB5547"},
Exception = {fg = "#D291F3"},
["@exception"] = {link = "Exception"},
Field = {fg = "#8490CD"},
["@field"] = {link = "Field"},
["@property"] = {link = "Field"},
["@float"] = {link = "Float"},
FoldColumn = {},
Folded = {},
Function = {fg = "#3DB8F5"},
["@function"] = {link = "Function"},
["@method"] = {link = "Function"},
GitSignsAdd = {fg = "#8FB83D"},
GitSignsAddPreview = {},
GitSignsChange = {fg = "#E29D12"},
GitSignsDelete = {fg = "#D62E1F"},
GitSignsDeletePreview = {},
Identifier = {fg = "#A8B2E1"},
["@variable"] = {link = "Identifier"},
IncSearch = {fg = "#21222C", bg = "#F0B642"},
["@include"] = {link = "Include"},
IndentBlanklineChar = {fg = "#474B62"},
IndentBlanklineIndent1 = {fg = "#474B62"},
IndentBlanklineIndent2 = {fg = "#404459"},
IndentBlanklineIndent3 = {fg = "#3C4053"},
IndentBlanklineIndent4 = {fg = "#36394A"},
IndentBlanklineIndent5 = {fg = "#2F3241"},
IndentBlanklineIndent6 = {fg = "#292B38"},
Keyword = {fg = "#D291F3"},
["@keyword"] = {link = "Keyword"},
Label = {fg = "#D291F3"},
["@label"] = {link = "Label"},
LineNr = {fg = "#4A506D"},
LspCodeLens = {fg = "#7C8DDE"},
LspCodeLensSeparator = {fg = "#3750CD"},
LspReferenceRead = {bg = "#E29D12"},
LspReferenceText = {bg = "#7C8DDE"},
LspReferenceWrite = {bg = "#D62E1F"},
LspSignatureActiveParameter = {fg = "#3DB8F5"},
["@constant.macro"] = {link = "Macro"},
["@function.macro"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
MatchParen = {bg = "#45495E"},
NonText = {fg = "#7C8DDE"},
NormalFloat = {},
NormalNC = {},
Number = {fg = "#3DB8F5"},
Float = {link = "Number"},
["@number"] = {link = "Number"},
NvimTreeFolderIcon = {fg = "#20ADF3"},
NvimTreeFolderName = {fg = "#C2C9F0"},
NvimTreeGitDeleted = {fg = "#E6594C"},
NvimTreeGitDirty = {fg = "#FA9938"},
NvimTreeGitNew = {fg = "#AACC66"},
NvimTreeImageFile = {},
NvimTreeIndentMarker = {fg = "#666F99"},
NvimTreeNormal = {bg = "#252732"},
NvimTreeNormalNC = {},
NvimTreeOpenedFile = {fg = "#3DB8F5"},
NvimTreeRootFolder = {fg = "#3DB8F5", bold = true},
NvimTreeSpecialFile = {fg = "#3DB8F5"},
NvimTreeSymlink = {},
NvimTreeWinSeparator = {fg = "#393E56", bg = "#252732"},
Operator = {fg = "#7481BE"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#C2C9F0", bg = "#343746"},
PmenuSbar = {bg = "#45495E"},
PmenuSel = {fg = "#21222C", bg = "#3DB8F5"},
PmenuThumb = {bg = "#6A7090"},
PreProc = {fg = "#DAA3F5"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
["@variable.builtin"] = {link = "PreProc"},
Repeat = {fg = "#D291F3"},
["@repeat"] = {link = "Repeat"},
Search = {fg = "#21222C", bg = "#E29D12"},
Substitute = {link = "Search"},
SignColumn = {},
Special = {fg = "#FA9938"},
SpecialChar = {link = "Special"},
Tag = {link = "Special"},
["@constant.builtin"] = {link = "Special"},
["@function.builtin"] = {link = "Special"},
["@parameter"] = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
Statement = {fg = "#D291F3"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#AACC66"},
["@string"] = {link = "String"},
["@namespace"] = {link = "Structure"},
["@structure"] = {link = "Structure"},
TSRainbowBlue = {fg = "#E87DB3"},
TSRainbowCyan = {fg = "#81D4E4"},
TSRainbowGreen = {fg = "#E0C285"},
TSRainbowOrange = {fg = "#E09485"},
TSRainbowRed = {fg = "#9485E0"},
TSRainbowViolet = {fg = "#70C299"},
TSRainbowYellow = {fg = "#D481E4"},
["@tag"] = {link = "Tag"},
["@text.reference"] = {link = "Tag"},
TermCursor = {},
TermCursorNC = {},
Title = {fg = "#DAA3F5"},
["@text.title"] = {link = "Title"},
Todo = {fg = "#F0B642", bold = true, italic = true},
["@text.todo"] = {link = "Todo"},
Type = {fg = "#52E0E0"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@type"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {undercurl = true},
["@text.underline"] = {link = "Underlined"},
["@text.uri"] = {link = "Underlined"},
VertSplit = {fg = "#343746"},
Visual = {bg = "#45495E"},
Whitespace = {fg = "#737891"},
SpecialKey = {link = "Whitespace"},
lCursor = {},
["@lsp.type.enumMember"] = {link = "@constant"},
["@lsp.type.class"] = {link = "@constructor"},
["@lsp.type.struct"] = {link = "@constructor"},
["@lsp.type.function"] = {link = "@function"},
["@lsp.type.interface"] = {link = "@keyword"},
["@lsp.type.macro"] = {link = "@macro"},
["@lsp.type.method"] = {link = "@method"},
["@lsp.type.namespace"] = {link = "@namespace"},
["@lsp.type.decorator"] = {link = "@parameter"},
["@lsp.type.parameter"] = {link = "@parameter"},
["@lsp.type.property"] = {link = "@property"},
["@slang.bold"] = {bold = true},
["@slang.code_block_content"] = {fg = "#BDC7EE"},
["@slang.code_block_end"] = {fg = "#7378a5", italic = true},
["@slang.code_block_fence"] = {bg = "#2f3041"},
["@slang.code_block_language"] = {fg = "#6F75A9", italic = true},
["@slang.code_block_start"] = {fg = "#7378a5", italic = true},
["@slang.comment"] = {fg = "#757DA3"},
["@slang.date"] = {fg = "#FC824A"},
["@slang.daterange"] = {fg = "#FC824A"},
["@slang.datetime"] = {fg = "#FC824A"},
["@slang.datetimerange"] = {fg = "#FC824A"},
["@slang.document.meta"] = {fg = "#F0B642"},
["@slang.document.meta.field"] = {fg = "#DAA3F5"},
["@slang.document.meta.field.key"] = {fg = "#F075B3"},
["@slang.document.title"] = {fg = "#FA9938", bold = true},
["@slang.error"] = {fg = "#ffffff", bg = "#7a2633"},
["@slang.external_link"] = {fg = "#5db4e3", italic = true, undercurl = true},
["@slang.heading_1.marker"] = {fg = "#9EADFA"},
["@slang.heading_1.text"] = {fg = "#9EADFA", bold = true},
["@slang.heading_2.marker"] = {fg = "#C08FFF"},
["@slang.heading_2.text"] = {fg = "#C08FFF", bold = true},
["@slang.heading_3.marker"] = {fg = "#E38FFF"},
["@slang.heading_3.text"] = {fg = "#E38FFF", bold = true},
["@slang.heading_4.marker"] = {fg = "#FFC78F"},
["@slang.heading_4.text"] = {fg = "#FFC78F", bold = true},
["@slang.heading_5.marker"] = {fg = "#04D3D0"},
["@slang.heading_5.text"] = {fg = "#04D3D0", bold = true},
["@slang.heading_6.marker"] = {fg = "#f0969f"},
["@slang.heading_6.text"] = {fg = "#f0969f", bold = true},
["@slang.heading_done"] = {fg = "#757DA3", bold = true},
["@slang.inline_code"] = {fg = "#fba03c"},
["@slang.italic"] = {italic = true},
["@slang.label"] = {fg = "#E7994B"},
["@slang.link"] = {fg = "#5BC0CD", italic = true, undercurl = true},
["@slang.list_item"] = {fg = "#A8B2E1"},
["@slang.list_item_label"] = {fg = "#c881de", bold = true},
["@slang.list_item_label_marker"] = {fg = "#757DA3"},
["@slang.list_item_marker"] = {fg = "#8995D2"},
["@slang.number"] = {fg = "#71c9f6"},
["@slang.section"] = {fg = "#93A4F6"},
["@slang.string"] = {fg = "#4efa8e"},
["@slang.tag.context"] = {fg = "#F0B642"},
["@slang.tag.danger"] = {fg = "#ffffff", bg = "#C3423F"},
["@slang.tag.hash"] = {fg = "#5BC0EB"},
["@slang.tag.identifier"] = {fg = "#e38fff"},
["@slang.tag.negative"] = {fg = "#FA4224"},
["@slang.tag.positive"] = {fg = "#9BC53D"},
["@slang.task_active"] = {fg = "#52E0E0"},
["@slang.task_cancelled"] = {fg = "#fa4040"},
["@slang.task_default"] = {},
["@slang.task_done"] = {fg = "#757DA3"},
["@slang.task_schedule"] = {fg = "#FF8000"},
["@slang.task_session"] = {fg = "#7378a5"},
["@slang.ticket"] = {fg = "#fa89f6"},
["@slang.time"] = {fg = "#FC824A"},
["@slang.timerange"] = {fg = "#FC824A"},
["@slang.underline"] = {underline = true},
["@lsp.type.typeParameter"] = {link = "@type.definition"},
["@lsp.type.enum"] = {link = "@type"},
["@lsp.type.type"] = {link = "@type"},
["@lsp.type.variable"] = {link = "@variable"},
  -- PATCH_CLOSE
}

vim.opt.background = "dark"
vim.g.colors_name = "static"
vim.cmd.highlight("clear")
-- vim.cmd.syntax("reset")

for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
