-- base colors
local colors = {
  -- PATCH_OPEN
Normal = {fg = "#C6C3D5"},
["@text"] = {link = "Normal"},
["@text.literal.markdown"] = {link = "Normal"},
Boolean = {fg = "#FF8170"},
["@boolean"] = {link = "Boolean"},
CWordHighlight = {bg = "#363442"},
Character = {fg = "#ACD35F"},
["@character"] = {link = "Character"},
CmpItemAbbr = {fg = "#C6C3D5"},
CmpItemAbbrDeprecated = {fg = "#7A7788", strikethrough = true},
CmpItemAbbrMatch = {fg = "#7EBDFC"},
CmpItemAbbrMatchFuzzy = {fg = "#7EBDFC", bold = true},
CmpItemKind = {fg = "#7EBDFC"},
CmpItemKindClass = {fg = "#17CFCF"},
CmpItemKindColor = {},
CmpItemKindConstant = {fg = "#FF8170"},
CmpItemKindConstructor = {fg = "#17CFCF"},
CmpItemKindCopilot = {fg = "#EC93D6"},
CmpItemKindEnum = {fg = "#17CFCF"},
CmpItemKindEnumMember = {fg = "#17CFCF"},
CmpItemKindEvent = {fg = "#17CFCF"},
CmpItemKindField = {fg = "#A5A0BA"},
CmpItemKindFile = {fg = "#7EBDFC"},
CmpItemKindFolder = {fg = "#7EBDFC"},
CmpItemKindFunction = {fg = "#7EBDFC"},
CmpItemKindInterface = {fg = "#17CFCF"},
CmpItemKindKeyword = {fg = "#918CAB"},
CmpItemKindMethod = {fg = "#7EBDFC"},
CmpItemKindModule = {fg = "#EDAF5E"},
CmpItemKindOperator = {fg = "#918CAB"},
CmpItemKindProperty = {fg = "#A5A0BA"},
CmpItemKindReference = {},
CmpItemKindSnippet = {fg = "#9485E0"},
CmpItemKindStruct = {fg = "#17CFCF"},
CmpItemKindText = {fg = "#C6C3D5"},
CmpItemKindTypeParameter = {fg = "#17CFCF"},
CmpItemKindUnit = {fg = "#17CFCF"},
CmpItemKindValue = {fg = "#FF8170"},
CmpItemKindVariable = {fg = "#C6C3D5"},
CmpItemMenu = {fg = "#7A7788"},
CodeBlock = {bg = "#282631"},
ColorColumn = {},
Comment = {fg = "#7A7788", italic = true},
SpecialComment = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@text.todo.checked"] = {link = "Comment"},
Conceal = {fg = "#AFABC4"},
Conditional = {fg = "#EF71C5"},
["@conditional"] = {link = "Conditional"},
["@keyword.repeat"] = {link = "Conditional"},
Constant = {fg = "#FF8170"},
["@constant"] = {link = "Constant"},
["@lsp.mod.constant"] = {link = "Constant"},
Constructor = {fg = "#17CFCF"},
["@constructor"] = {link = "Constructor"},
Cursor = {fg = "#211F28", bg = "#C6C3D5"},
TermCursor = {link = "Cursor"},
TermCursorNC = {link = "Cursor"},
CursorColumn = {},
CursorIM = {},
CursorLine = {bg = "#2A2833"},
CursorLineNr = {fg = "#89849F", bg = "#363442"},
CursorLineSign = {fg = "#EB9147", bg = "#363442"},
CursorWord = {bg = "#363442"},
Debug = {fg = "#E02A06"},
["@debug"] = {link = "Debug"},
["@constant.macro"] = {link = "Define"},
["@define"] = {link = "Define"},
Delimiter = {fg = "#746F8B"},
["@constructor.lua"] = {link = "Delimiter"},
["@punctuation"] = {link = "Delimiter"},
["@punctuation.bracket"] = {link = "Delimiter"},
["@punctuation.delimiter"] = {link = "Delimiter"},
["@punctuation.special"] = {link = "Delimiter"},
["@tag.delimiter"] = {link = "Delimiter"},
DiagnosticError = {fg = "#E02A06"},
DiagnosticFloatingError = {fg = "#E02A06"},
DiagnosticFloatingHint = {fg = "#17CFCF"},
DiagnosticFloatingInfo = {fg = "#7EBDFC"},
DiagnosticFloatingWarn = {fg = "#EB9147"},
DiagnosticHint = {fg = "#17CFCF"},
DiagnosticInfo = {fg = "#7EBDFC"},
DiagnosticSignError = {fg = "#E02A06"},
DiagnosticSignHint = {fg = "#17CFCF"},
DiagnosticSignInfo = {fg = "#7EBDFC"},
DiagnosticSignWarn = {fg = "#EB9147"},
DiagnosticUnderlineError = {bg = "#803323"},
DiagnosticUnderlineHint = {undercurl = true},
DiagnosticUnderlineInfo = {undercurl = true},
DiagnosticUnderlineWarn = {undercurl = true},
DiagnosticUnnecessary = {undercurl = true},
DiagnosticVirtualTextError = {fg = "#E02A06"},
DiagnosticVirtualTextHint = {fg = "#17CFCF"},
DiagnosticVirtualTextInfo = {fg = "#7EBDFC"},
DiagnosticVirtualTextWarn = {fg = "#EB9147"},
DiagnosticWarn = {fg = "#EB9147"},
DiffAdd = {fg = "#ACD35F"},
MiniDiffSignAdd = {link = "DiffAdd"},
DiffChange = {fg = "#EDAF5E"},
MiniDiffSignChange = {link = "DiffChange"},
DiffDelete = {fg = "#E02A06"},
MiniDiffSignDelete = {link = "DiffDelete"},
DiffText = {fg = "#7EBDFC"},
DimmedComment = {fg = "#5C5874", italic = true},
Directory = {fg = "#7EBDFC"},
EndOfBuffer = {fg = "#211F28"},
Error = {fg = "#E02A06"},
["@error"] = {link = "Error"},
ErrorMsg = {fg = "#E12905"},
["@text.danger"] = {link = "ErrorMsg"},
Exception = {fg = "#EB806B"},
["@exception"] = {link = "Exception"},
["@keyword.exception"] = {link = "Exception"},
Field = {fg = "#A5A0BA"},
["@field"] = {link = "Field"},
["@float"] = {link = "Float"},
FoldColumn = {},
Folded = {},
Function = {fg = "#7EBDFC"},
["@function.call"] = {link = "Function"},
["@function.method.call"] = {link = "Function"},
["@method"] = {link = "Function"},
["@method.call"] = {link = "Function"},
Headline1 = {bg = "#2A2938"},
Headline2 = {bg = "#2F3042"},
Headline3 = {bg = "#313749"},
Headline4 = {bg = "#3D434D"},
Headline5 = {bg = "#414B53"},
Headline6 = {bg = "#48565B"},
HighlightUndo = {fg = "#EB9147", bg = "#8A460F"},
Identifier = {fg = "#C6C3D5"},
["@lsp.type.identifier"] = {link = "Identifier"},
["@lsp.typemod.function.declaration"] = {link = "Identifier"},
["@lsp.typemod.variable"] = {link = "Identifier"},
["@symbol"] = {link = "Identifier"},
["@tag.attribute"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
IncSearch = {fg = "#211F28", bg = "#EDAF5E"},
["@include"] = {link = "Include"},
Keyword = {fg = "#918CAB"},
["@keyword"] = {link = "Keyword"},
Label = {fg = "#918CAB"},
["@label"] = {link = "Label"},
LeapLabelPrimary = {fg = "#EFA76C", bg = "#8A460F"},
Lens = {fg = "#4A4856"},
LineNr = {fg = "#494659"},
LspCodeLens = {fg = "#9893B4"},
LspCodeLensSeparator = {fg = "#6C6490"},
LspInlayHint = {fg = "#5F5C70"},
LspReferenceRead = {bg = "#E79223"},
LspReferenceText = {bg = "#9893B4"},
LspReferenceWrite = {bg = "#B32205"},
LspSignatureActiveParameter = {fg = "#7EBDFC"},
Macro = {fg = "#A798F0"},
["@function.macro"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
["@text.environment"] = {link = "Macro"},
MatchParen = {bg = "#494659"},
NonText = {fg = "#9893B4"},
NormalFloat = {bg = "#2A2833"},
NormalNC = {},
NotifyBackground = {bg = "#211F28"},
Number = {fg = "#FF8170"},
Float = {link = "Number"},
["@number"] = {link = "Number"},
NvimTreeFolderIcon = {fg = "#5BABFB"},
NvimTreeFolderName = {fg = "#C6C3D5"},
NvimTreeGitDeleted = {fg = "#E02A06"},
NvimTreeGitDirty = {fg = "#EB9147"},
NvimTreeGitNew = {fg = "#ACD35F"},
NvimTreeImageFile = {},
NvimTreeIndentMarker = {fg = "#6D6B7B"},
NvimTreeNormal = {bg = "#26242E"},
NvimTreeNormalNC = {},
NvimTreeOpenedFile = {fg = "#7EBDFC"},
NvimTreeRootFolder = {fg = "#7EBDFC", bold = true},
NvimTreeSpecialFile = {fg = "#7EBDFC"},
NvimTreeSymlink = {},
NvimTreeWinSeparator = {fg = "#3D3B44", bg = "#26242E"},
Operator = {fg = "#918CAB"},
["@operator"] = {link = "Operator"},
Parameter = {fg = "#E3AC63"},
["@parameter"] = {link = "Parameter"},
Pmenu = {fg = "#C6C3D5", bg = "#363442"},
PmenuSbar = {bg = "#494659"},
PmenuSel = {fg = "#211F28", bg = "#7EBDFC"},
PmenuThumb = {bg = "#716C89"},
PreProc = {fg = "#918CAB"},
["@attribute"] = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Property = {fg = "#A5A0BA"},
["@property"] = {link = "Property"},
Quote = {fg = "#38425B", bold = true},
RainbowBlue = {fg = "#5CADD6"},
RainbowCyan = {fg = "#66CCCC"},
RainbowGreen = {fg = "#AACC66"},
RainbowOrange = {fg = "#F6A655"},
RainbowRed = {fg = "#E48191"},
RainbowViolet = {fg = "#B093EC"},
RainbowYellow = {fg = "#D6AD5C"},
RenderMarkdownBullet = {fg = "#A294EB"},
RenderMarkdownChecked = {fg = "#77767F"},
RenderMarkdownCode = {bg = "#282631"},
RenderMarkdownCodeBorder = {bg = "#2D2B36"},
RenderMarkdownCodeInline = {fg = "#ED9145"},
RenderMarkdownH1 = {fg = "#C6C3D5"},
RenderMarkdownH1Bg = {bg = "#2A2938"},
RenderMarkdownH2 = {fg = "#C6C3D5"},
RenderMarkdownH2Bg = {bg = "#2F3042"},
RenderMarkdownH3 = {fg = "#C6C3D5"},
RenderMarkdownH3Bg = {bg = "#313749"},
RenderMarkdownH4 = {fg = "#C6C3D5"},
RenderMarkdownH4Bg = {bg = "#3D434D"},
RenderMarkdownH5 = {fg = "#C6C3D5"},
RenderMarkdownH5Bg = {bg = "#414B53"},
RenderMarkdownH6 = {fg = "#C6C3D5"},
RenderMarkdownH6Bg = {bg = "#48565B"},
RenderMarkdownLink = {fg = "#6BABEB"},
RenderMarkdownQuote = {fg = "#EDAF5E"},
RenderMarkdownUnchecked = {fg = "#77767F"},
Repeat = {fg = "#EF71C5"},
["@repeat"] = {link = "Repeat"},
Search = {fg = "#211F28", bg = "#E79223"},
Substitute = {link = "Search"},
SignColumn = {},
SnacksProfilerHot01 = {bg = "#0F0A29"},
SnacksProfilerHot02 = {bg = "#140D35"},
SnacksProfilerHot03 = {bg = "#170F3D"},
SnacksProfilerHot04 = {bg = "#1C1249"},
SnacksProfilerHot05 = {bg = "#201556"},
SnacksProfilerHot06 = {bg = "#251862"},
SnacksProfilerHot07 = {bg = "#291C6E"},
SnacksProfilerHot08 = {bg = "#733B0D"},
SnacksProfilerHot09 = {bg = "#81420E"},
SnacksProfilerHot10 = {bg = "#8A460F"},
SnacksProfilerHot11 = {bg = "#934B10"},
SnacksProfilerHot12 = {bg = "#A15212"},
SnacksProfilerHot13 = {bg = "#AA5713"},
SnacksProfilerHot14 = {bg = "#B85E14"},
SnacksProfilerHot15 = {bg = "#9F1E04"},
SnacksProfilerHot16 = {bg = "#A41F04"},
SnacksProfilerHot17 = {bg = "#AE2104"},
SnacksProfilerHot18 = {bg = "#B82305"},
SnacksProfilerHot19 = {bg = "#C22405"},
SnacksProfilerHot20 = {bg = "#CC2605"},
Special = {fg = "#FF80AA"},
SpecialChar = {link = "Special"},
Tag = {link = "Special"},
["@tag.attribute.tsx"] = {link = "Special"},
["@text.math"] = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
["@text.note"] = {link = "SpecialComment"},
SpecialKeyword = {fg = "#FF80AA"},
Define = {link = "SpecialKeyword"},
Include = {link = "SpecialKeyword"},
PreCondit = {link = "SpecialKeyword"},
["@keyword.coroutine"] = {link = "SpecialKeyword"},
["@keyword.operator"] = {link = "SpecialKeyword"},
["@tag.tsx"] = {link = "SpecialKeyword"},
Statement = {fg = "#918CAB"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#ACD35F"},
["@string"] = {link = "String"},
["@string.regex"] = {link = "String"},
["@text.literal"] = {link = "String"},
["@structure"] = {link = "Structure"},
TabLine = {bg = "#211F28"},
TabLineFill = {bg = "#211F28"},
TabLineSel = {bg = "#211F28"},
["@tag"] = {link = "Tag"},
Title = {fg = "#F075D1"},
["@text.title"] = {link = "Title"},
Todo = {fg = "#EDAF5E", bold = true, italic = true},
["@text.todo"] = {link = "Todo"},
["@text.todo.unchecked"] = {link = "Todo"},
TreesitterContext = {bg = "#332A28"},
TreesitterContextLineNumber = {fg = "#816A65", bg = "#332A28"},
TreesitterContextLineNumberBottom = {underline = true},
Type = {fg = "#17CFCF"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@function"] = {link = "Type"},
["@namespace"] = {link = "Type"},
["@text.environment.name"] = {link = "Type"},
["@type"] = {link = "Type"},
["@type.qualifier"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {undercurl = true},
["@text.reference"] = {link = "Underlined"},
["@text.underline"] = {link = "Underlined"},
["@text.uri"] = {link = "Underlined"},
VertSplit = {fg = "#2A2833"},
Winseparator = {link = "VertSplit"},
Visual = {bg = "#471F5C"},
WarningMsg = {},
["@text.warning"] = {link = "WarningMsg"},
Whitespace = {fg = "#77767F"},
SpecialKey = {link = "Whitespace"},
WinBar = {fg = "#2EB8B8", bg = "#332F46", bold = true},
WinBarNC = {link = "WinBar"},
lCursor = {},
["@lsp.typemod.deriveHelper.attribute"] = {link = "@attribute"},
["@constant.builtin"] = {link = "@boolean"},
["@lsp.type.boolean"] = {link = "@boolean"},
["@break"] = {fg = "#EB806B"},
["@keyword.function"] = {link = "@break"},
["@keyword.function.lua"] = {link = "@break"},
["@keyword.return"] = {link = "@break"},
["@builtin"] = {fg = "#EB806B"},
["@function.builtin"] = {link = "@builtin"},
["@lsp.typemod.class.defaultLibrary"] = {link = "@builtin"},
["@lsp.typemod.function.defaultLibrary"] = {link = "@builtin"},
["@lsp.typemod.type.defaultLibrary"] = {link = "@builtin"},
["@lsp.typemod.variable.defaultLibrary"] = {link = "@builtin"},
["@namespace.builtin.lua"] = {link = "@builtin"},
["@variable.builtin"] = {link = "@builtin"},
["@lsp.type.character"] = {link = "@character"},
["@keyword.conditional"] = {link = "@conditional"},
["@lsp.type.enumMember"] = {link = "@constant"},
["@lsp.type.namespace"] = {link = "@constant"},
["@constructor.tsx"] = {},
["@lsp.type.class"] = {link = "@constructor"},
["@lsp.typemod.property.declaration"] = {link = "@field"},
["@lsp.type.float"] = {link = "@float"},
["@lsp.mod.readonly"] = {},
["@lsp.mod.static"] = {italic = true},
["@lsp.type.event"] = {fg = "#EB9147"},
["@lsp.type.function"] = {},
["@lsp.type.keyword"] = {},
["@lsp.type.lifetime"] = {fg = "#EC93D6"},
["@lsp.type.operator"] = {fg = "#EF71C5"},
["@lsp.typemod.function"] = {},
["@lsp.typemod.string.constant"] = {},
["@lsp.typemod.string.readonly"] = {},
["@lsp.typemod.string.static"] = {},
["@lsp.mod.annotation"] = {link = "@macro"},
["@lsp.type.macro"] = {link = "@macro"},
["@markup.link.label.markdown_inline"] = {fg = "#5BC0CD"},
["@markup.link.markdown_inline"] = {fg = "#5BC0CD"},
["@markup.raw.markdown_inline"] = {fg = "#ED9145"},
["@lsp.type.method"] = {link = "@method"},
["@none"] = {fg = "NONE", bg = "NONE"},
["@lsp.type.number"] = {link = "@number"},
["@lsp.type.decorator"] = {link = "@parameter"},
["@lsp.type.parameter"] = {link = "@parameter"},
["@lsp.type.property"] = {link = "@property"},
["@slang.banner"] = {fg = "#A9B9E5", bg = "#38425B"},
["@slang.bold"] = {bold = true},
["@slang.code_block_content"] = {fg = "#C6C3D5"},
["@slang.code_block_end"] = {fg = "#494659", italic = true},
["@slang.code_block_fence"] = {bg = "#282631"},
["@slang.code_block_language"] = {fg = "#5E5A72", italic = true},
["@slang.code_block_start"] = {fg = "#494659", italic = true},
["@slang.comment"] = {fg = "#7A7788"},
["@slang.date"] = {fg = "#FC824A"},
["@slang.daterange"] = {fg = "#FC824A"},
["@slang.datetime"] = {fg = "#FC824A"},
["@slang.datetimerange"] = {fg = "#FC824A"},
["@slang.document.meta"] = {fg = "#7A7788"},
["@slang.document.meta.field"] = {fg = "#F075D1"},
["@slang.document.meta.field.key"] = {fg = "#EC93D6"},
["@slang.document.title"] = {fg = "#C0E774", bold = true},
["@slang.error"] = {fg = "#ffffff", bg = "#7a2633"},
["@slang.external_link"] = {fg = "#6BABEB", italic = true},
["@slang.heading_1.marker"] = {fg = "#9B96B0"},
["@slang.heading_1.text"] = {fg = "#C6C3D5", bold = true},
["@slang.heading_2.marker"] = {fg = "#9B96B0"},
["@slang.heading_2.text"] = {fg = "#C6C3D5", bold = true},
["@slang.heading_3.marker"] = {fg = "#9B96B0"},
["@slang.heading_3.text"] = {fg = "#C6C3D5", bold = true},
["@slang.heading_4.marker"] = {fg = "#9B96B0"},
["@slang.heading_4.text"] = {fg = "#C6C3D5", bold = true},
["@slang.heading_5.marker"] = {fg = "#9B96B0"},
["@slang.heading_5.text"] = {fg = "#C6C3D5", bold = true},
["@slang.heading_6.marker"] = {fg = "#9B96B0"},
["@slang.heading_6.text"] = {fg = "#C6C3D5", bold = true},
["@slang.image"] = {fg = "#E486CC"},
["@slang.inline_code"] = {fg = "#ED9145"},
["@slang.internal_link"] = {fg = "#5BC0CD"},
["@slang.italic"] = {italic = true},
["@slang.label"] = {fg = "#E486CC"},
["@slang.label_line"] = {fg = "#20C5C5"},
["@slang.link"] = {fg = "#5BC0CD", italic = true},
["@slang.list_item"] = {},
["@slang.list_item_label"] = {fg = "#A294EB"},
["@slang.list_item_label_marker"] = {fg = "#7A7788"},
["@slang.list_item_marker"] = {fg = "#77767F"},
["@slang.number"] = {fg = "#FF8170"},
["@slang.outline_1.marker"] = {fg = "#9999FF"},
["@slang.outline_1.text"] = {fg = "#9999FF", bold = true},
["@slang.outline_2.marker"] = {fg = "#BF8FFF"},
["@slang.outline_2.text"] = {fg = "#BF8FFF", bold = true},
["@slang.outline_3.marker"] = {fg = "#E38FFF"},
["@slang.outline_3.text"] = {fg = "#E38FFF", bold = true},
["@slang.outline_4.marker"] = {fg = "#FFC78F"},
["@slang.outline_4.text"] = {fg = "#FFC78F", bold = true},
["@slang.outline_5.marker"] = {fg = "#04D2CE"},
["@slang.outline_5.text"] = {fg = "#04D2CE", bold = true},
["@slang.outline_6.marker"] = {fg = "#F0949D"},
["@slang.outline_6.text"] = {fg = "#F0949D", bold = true},
["@slang.outline_done"] = {fg = "#62606C", bold = true},
["@slang.section"] = {fg = "#8797C2"},
["@slang.string"] = {fg = "#ACD35F"},
["@slang.tag.context"] = {fg = "#EDAF5E"},
["@slang.tag.danger"] = {fg = "#ffffff", bg = "#C3423F"},
["@slang.tag.hash"] = {fg = "#5BC0EB"},
["@slang.tag.identifier"] = {fg = "#e38fff"},
["@slang.tag.negative"] = {fg = "#FA4224"},
["@slang.tag.positive"] = {fg = "#9BC53D"},
["@slang.task_active"] = {fg = "#17CFCF"},
["@slang.task_cancelled"] = {fg = "#fa4040"},
["@slang.task_completion"] = {fg = "#7378a5"},
["@slang.task_default"] = {},
["@slang.task_done"] = {fg = "#62606C"},
["@slang.task_marker_default"] = {fg = "#62606C"},
["@slang.task_recurrence"] = {fg = "#7378a5"},
["@slang.task_schedule"] = {fg = "#7378a5"},
["@slang.task_session"] = {fg = "#7378a5"},
["@slang.ticket"] = {fg = "#fa89f6"},
["@slang.time"] = {fg = "#FC824A"},
["@slang.timerange"] = {fg = "#FC824A"},
["@slang.underline"] = {underline = true},
["@lsp.mod.interpolation"] = {link = "@string.special"},
["@lsp.type.string"] = {link = "@string"},
["@lsp.type.struct"] = {link = "@structure"},
["@text.emphasis"] = {italic = true},
["@text.literal.markdown_inline"] = {fg = "#ED9145"},
["@text.literal.syslang"] = {fg = "#C6C3D5"},
["@text.strike"] = {strikethrough = true},
["@text.strong"] = {bold = true},
["@lsp.type.typeAlias"] = {link = "@type.definition"},
["@lsp.type.enum"] = {link = "@type"},
["@lsp.type.interface"] = {link = "@type"},
["@lsp.type.type"] = {link = "@type"},
["@lsp.type.typeParameter"] = {link = "@type"},
["@lsp.typemod.interface"] = {link = "@type"},
["@lsp.typemod.type.readonly"] = {link = "@type"},
["@lsp.typemod.typeParameter"] = {link = "@type"},
["@type.builtin"] = {link = "@type"},
["@lsp.type.variable"] = {link = "@variable"},
  -- PATCH_CLOSE
}

-- host-specific overrides
local hostname = vim.loop.os_gethostname()
-- if hostname == "death" then
-- colors.CursorLine = {}
-- colors.NvimTreeNormal = {}
-- colors.NvimTreeWinSeparator = { fg = "#3A364E" }
-- colors.TabLine = {}
-- colors.TabLineFill = {}
-- colors.TabLineSel = {}
-- colors.WinBar = { bg = "#110F18", fg = "#2EB8B8", bold = true }
-- colors["@slang.banner"] = { fg = "#A9B9E5" }
-- end

vim.opt.background = "dark"
vim.g.colors_name = "static"
vim.cmd.highlight("clear")
-- vim.cmd.syntax("reset")

for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
