{
 "title": "Event Explorer",
 "tags": [
  "core",
  "monitoring",
  "events"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "process_filter", "label": "Process Regex", "query": ".*" },
   { "name": "path_filter", "label": "Path Regex", "query": ".*" },
   { "name": "endpoint_filter", "label": "Endpoint Regex", "query": ".*" },
   { "name": "scope_filter", "label": "Scope Regex", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Recent Exec Events",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"audit_exec\"} | json | __error__=\"\" | kind=\"audit_exec_event\" | exe!~\"^[0-9A-Fa-f]{16,}$\" | cmdline!~\".*core-monitoring.*\" | cmdline!~\".*ausearch --input-logs.*\" | comm=~\"$process_filter\" | line_format `exe={{.exe}} comm={{.comm}} pid={{.pid}} argv={{.argv}} cmdline={{.cmdline}} uid={{.uid}} auid={{.auid}} success={{.success}}`"
    }
   ]
  },
  {
   "title": "Recent Outbound Connections",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"audit_net\"} | json | __error__=\"\" | kind=\"audit_net_event\" | family=~\"^inet.*$\" | dest_target!=\"\" | dest_target=~\"$endpoint_filter\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm=~\"$process_filter\" | line_format `exe={{.exe}} comm={{.comm}} pid={{.pid}} target={{.dest_target}} ip={{.dest_ip}} port={{.dest_port}} location={{.country_name}} cc={{.country_code}} success={{.success}} cmdline={{.cmdline}}`"
    }
   ]
  },
  {
   "title": "Recent Watched-Path Writes",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{component=\"audit_fs\"} | json | __error__=\"\" | kind=\"audit_fs_event\" | scope=~\"$scope_filter\" | watched_root!=\"\" | path=~\"$path_filter\" | comm!~\"^(alloy|auditd|ausearch|core-monitoring.*|grafana|loki)$\" | comm=~\"$process_filter\" | line_format `scope={{.scope}} exe={{.exe}} comm={{.comm}} pid={{.pid}} root={{.watched_root}} path={{.path}} nametype={{.nametype}} success={{.success}} cmdline={{.cmdline}}`"
    }
   ]
  }
 ]
}