{
 "title": "Network",
 "tags": [
  "core",
  "monitoring",
  "network"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "process_filter", "label": "Process Regex", "query": ".*" },
   { "name": "endpoint_filter", "label": "Endpoint Regex", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Top Remote Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(100, sum by (dest_target, dest_ip, dest_port, country_name, country_code) (sum_over_time({component=\"audit_net_summary\",summary_kind=\"by_endpoint_process\"} | json | __error__=\"\" | family=~\"^inet.*$\" | dest_target!=\"\" | dest_target=~\"$endpoint_filter\" | dest_ip!=\"\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm!~\"^[0-9A-Fa-f]{6,}$\" | comm=~\"$process_filter\" | unwrap count [$__range])))"
    }
   ]
  },
  {
   "title": "Top Connecting Processes",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "topk(100, sum by (exe) (sum_over_time({component=\"audit_net_summary\",summary_kind=\"by_endpoint_process\"} | json | __error__=\"\" | family=~\"^inet.*$\" | dest_target!=\"\" | dest_target=~\"$endpoint_filter\" | exe!=\"\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm!~\"^[0-9A-Fa-f]{6,}$\" | comm=~\"$process_filter\" | unwrap count [$__range])))"
    }
   ]
  },
  {
   "title": "Top Network Traffic Processes",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(100, max by (cmd) (max_over_time({component=\"net_usage\"} | json | __error__=\"\" | cmd=~\"$process_filter\" | unwrap total_kib_s [$__range])))"
    }
   ]
  },
  {
   "title": "Top Destination Countries",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "topk(100, sum by (country_name, country_code) (sum_over_time({component=\"audit_net_summary\",summary_kind=\"by_endpoint_process\"} | json | __error__=\"\" | family=~\"^inet.*$\" | dest_target!=\"\" | dest_target=~\"$endpoint_filter\" | dest_ip!=\"\" | country_code!=\"\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm=~\"$process_filter\" | unwrap count [$__range])))"
    }
   ]
  },
  {
   "title": "Connect Rate By Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, sum by (exe) (last_over_time({component=\"audit_net_summary\",summary_kind=\"by_endpoint_process\"} | json | __error__=\"\" | family=~\"^inet.*$\" | dest_target!=\"\" | dest_target=~\"$endpoint_filter\" | exe!=\"\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm!~\"^[0-9A-Fa-f]{6,}$\" | comm=~\"$process_filter\" | unwrap count [1m])))",
     "legendFormat": "{{exe}}"
    }
   ]
  },
  {
   "title": "Network Traffic Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, max by (cmd) (last_over_time({component=\"net_usage\"} | json | __error__=\"\" | cmd=~\"$process_filter\" | unwrap total_kib_s [1m])))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Remote Endpoints Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by (dest_target) (last_over_time({component=\"audit_net_summary\",summary_kind=\"by_endpoint_process\"} | json | __error__=\"\" | family=~\"^inet.*$\" | dest_target!=\"\" | dest_target=~\"$endpoint_filter\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm!~\"^[0-9A-Fa-f]{6,}$\" | comm=~\"$process_filter\" | unwrap count [1m])))",
     "legendFormat": "{{dest_target}}"
    }
   ]
  },
  {
   "title": "Destination Country Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "sum by (country_code, country_name) (sum_over_time({component=\"audit_net_summary\",summary_kind=\"by_endpoint_process\"} | json | __error__=\"\" | family=~\"^inet.*$\" | dest_target!=\"\" | dest_target=~\"$endpoint_filter\" | dest_ip!=\"\" | country_code!=\"\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm=~\"$process_filter\" | unwrap count [$__range]))"
    }
   ]
  },
  {
   "title": "Recent Outbound Connections",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{component=\"audit_net\"} | json | __error__=\"\" | kind=\"audit_net_event\" | family=~\"^inet.*$\" | dest_target!=\"\" | dest_target=~\"$endpoint_filter\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm!~\"^[0-9A-Fa-f]{6,}$\" | comm=~\"$process_filter\" | line_format `exe={{.exe}} comm={{.comm}} pid={{.pid}} target={{.dest_target}} ip={{.dest_ip}} port={{.dest_port}} location={{.country_name}} cc={{.country_code}} success={{.success}} cmdline={{.cmdline}}`"
    }
   ]
  }
 ]
}