{
 "title": "Triage",
 "tags": [
  "core",
  "monitoring",
  "triage"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "process_filter", "label": "Process Regex", "query": ".*" },
   { "name": "path_filter", "label": "Path Regex", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Exec Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({component=\"audit_exec_summary\",summary_kind=\"window_total\"} | json | __error__=\"\" | unwrap count [$__range]))"
    }
   ]
  },
  {
   "title": "Remote Connects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({component=\"audit_net_summary\",summary_kind=\"by_endpoint_process\"} | json | __error__=\"\" | family=~\"^inet.*$\" | dest_target!=\"\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm=~\"$process_filter\" | unwrap count [$__range]))"
    }
   ]
  },
  {
   "title": "File Writes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({component=\"audit_fs_summary\",summary_kind=\"by_path_process\"} | json | __error__=\"\" | watched_root!=\"\" | path=~\"$path_filter\" | comm!~\"^(alloy|auditd|ausearch|core-monitoring.*|grafana|loki)$\" | comm=~\"$process_filter\" | unwrap count [$__range]))"
    }
   ]
  },
  {
   "title": "Unique Executables",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (exe) (max_over_time({component=\"audit_exec_summary\",summary_kind=\"by_exe\"} | json | __error__=\"\" | exe!=\"\" | exe!~\"^[0-9A-Fa-f]{16,}$\" | cmdline!~\".*core-monitoring.*\" | cmdline!~\".*ausearch --input-logs.*\" | comm=~\"$process_filter\" | unwrap count [$__range])))"
    }
   ]
  },
  {
   "title": "Unique Remote Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (dest_target) (max_over_time({component=\"audit_net_summary\",summary_kind=\"by_endpoint_process\"} | json | __error__=\"\" | family=~\"^inet.*$\" | dest_target!=\"\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm=~\"$process_filter\" | unwrap count [$__range])))"
    }
   ]
  },
  {
   "title": "Anomalies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({component=\"anomaly\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Top CPU Processes",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "topk(100, max by (cmd, exe, comm) (last_over_time(core_monitoring_process_cpu_percent{comm=~\"$process_filter\", exe=~\".+\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Top Connecting Processes",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "topk(100, sum by (exe) (sum_over_time({component=\"audit_net_summary\",summary_kind=\"by_endpoint_process\"} | json | __error__=\"\" | family=~\"^inet.*$\" | dest_target!=\"\" | exe!=\"\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm!~\"^[0-9A-Fa-f]{6,}$\" | comm=~\"$process_filter\" | unwrap count [$__range])))"
    }
   ]
  },
  {
   "title": "Top Writing Processes",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "topk(100, sum by (exe) (sum_over_time({component=\"audit_fs_summary\",summary_kind=\"by_path_process\"} | json | __error__=\"\" | watched_root!=\"\" | exe!=\"\" | path=~\"$path_filter\" | comm!~\"^(alloy|auditd|ausearch|core-monitoring.*|grafana|loki)$\" | comm=~\"$process_filter\" | unwrap count [$__range])))"
    }
   ]
  },
  {
   "title": "CPU Leaders Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(5, max by (exe, cmd) (last_over_time(core_monitoring_process_cpu_percent{comm=~\"$process_filter\", exe=~\".+\"}[1m])))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Outbound Connections Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "topk(5, sum by (exe) (last_over_time({component=\"audit_net_summary\",summary_kind=\"by_endpoint_process\"} | json | __error__=\"\" | family=~\"^inet.*$\" | dest_target!=\"\" | exe!=\"\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm!~\"^[0-9A-Fa-f]{6,}$\" | comm=~\"$process_filter\" | unwrap count [1m])))",
     "legendFormat": "{{exe}}"
    }
   ]
  },
  {
   "title": "Write Activity By Scope",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum by (scope) (last_over_time({component=\"audit_fs_summary\",summary_kind=\"by_path_process\"} | json | __error__=\"\" | watched_root!=\"\" | path=~\"$path_filter\" | comm!~\"^(alloy|auditd|ausearch|core-monitoring.*|grafana|loki)$\" | comm=~\"$process_filter\" | unwrap count [1m]))",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Recent Abnormal And New Processes",
   "type": "logs",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{component=\"anomaly\"} | json | __error__=\"\" | line_format `{{.anomaly_type}} severity={{.severity}} source={{.source_component}} message={{.message}} exe={{.exe}} cmd={{.cmd}} comm={{.comm}} pid={{.pid}}`"
    }
   ]
  },
  {
   "title": "Recent Outbound Connections",
   "type": "logs",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "{component=\"audit_net\"} | json | __error__=\"\" | kind=\"audit_net_event\" | family=~\"^inet.*$\" | dest_target!=\"\" | dest_ip!~\"^(::ffff:)?(127[.].*|10[.].*|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.].*|169[.]254[.].*|172[.](1[6-9]|2[0-9]|3[0-1])[.].*|192[.]168[.].*|0[.]0[.]0[.]0)$|^::1$\" | dest_port!=\"\" | dest_port!=\"0\" | dest_port!=\"65535\" | comm=~\"$process_filter\" | line_format `exe={{.exe}} comm={{.comm}} pid={{.pid}} target={{.dest_target}} ip={{.dest_ip}} port={{.dest_port}} family={{.family}} success={{.success}} cmdline={{.cmdline}}`"
    }
   ]
  },
  {
   "title": "Recent Watched-Path Writes",
   "type": "logs",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "{component=\"audit_fs\"} | json | __error__=\"\" | kind=\"audit_fs_event\" | watched_root!=\"\" | path=~\"$path_filter\" | comm!~\"^(alloy|auditd|ausearch|core-monitoring.*|grafana|loki)$\" | comm=~\"$process_filter\" | line_format `scope={{.scope}} exe={{.exe}} comm={{.comm}} pid={{.pid}} root={{.watched_root}} path={{.path}} nametype={{.nametype}} success={{.success}} cmdline={{.cmdline}}`"
    }
   ]
  }
 ]
}